-- CreateEnum
CREATE TYPE "ScoringPreset" AS ENUM ('CLASSIC_BEST_OF_3', 'CLASSIC_BEST_OF_5', 'CLASSIC_PRO_SET', 'CLASSIC_SHORT_SET', 'CLASSIC_SUPER_TIEBREAK', 'POINTS_16', 'POINTS_21', 'POINTS_24', 'POINTS_32', 'TIMED', 'CUSTOM');

-- AlterTable
ALTER TABLE "Game" ADD COLUMN     "hasGoldenPoint" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "scoringPreset" "ScoringPreset";
