-- AlterEnum
ALTER TYPE "PriceCurrency" ADD VALUE IF NOT EXISTS 'AED';
ALTER TYPE "PriceCurrency" ADD VALUE IF NOT EXISTS 'SAR';
ALTER TYPE "PriceCurrency" ADD VALUE IF NOT EXISTS 'QAR';
ALTER TYPE "PriceCurrency" ADD VALUE IF NOT EXISTS 'KWD';
ALTER TYPE "PriceCurrency" ADD VALUE IF NOT EXISTS 'OMR';
