export const ChatSyncEventType = {
  MESSAGE_CREATED: 'MESSAGE_CREATED',
  MESSAGE_UPDATED: 'MESSAGE_UPDATED',
  MESSAGE_DELETED: 'MESSAGE_DELETED',
  REACTION_ADDED: 'REACTION_ADDED',
  REACTION_REMOVED: 'REACTION_REMOVED',
  POLL_VOTED: 'POLL_VOTED',
  MESSAGE_TRANSCRIPTION_UPDATED: 'MESSAGE_TRANSCRIPTION_UPDATED',
  MESSAGE_READ_RECEIPT: 'MESSAGE_READ_RECEIPT',
  MESSAGE_TRANSLATION_UPDATED: 'MESSAGE_TRANSLATION_UPDATED',
  MESSAGES_READ_BATCH: 'MESSAGES_READ_BATCH',
  MESSAGE_PINNED: 'MESSAGE_PINNED',
  MESSAGE_UNPINNED: 'MESSAGE_UNPINNED',
  MESSAGE_STATE_UPDATED: 'MESSAGE_STATE_UPDATED',
  THREAD_LOCAL_INVALIDATE: 'THREAD_LOCAL_INVALIDATE',
  THREAD_ARCHIVED: 'THREAD_ARCHIVED',
  CHAT_AUTO_TRANSLATE_CONFIG_UPDATED: 'CHAT_AUTO_TRANSLATE_CONFIG_UPDATED',
} as const;

export type ChatSyncEventType = (typeof ChatSyncEventType)[keyof typeof ChatSyncEventType];

export const CHAT_SYNC_EVENT_TYPES = Object.values(ChatSyncEventType);
