/**
 * Backend copy for PRD 349 (live-start push) and PRD 356 (`/play`, `/live`).
 *
 * Kept out of `utils/translations.ts` for the same reason PRD 345 kept
 * `gameSeriesCopy.ts` separate: that file is one flat object per locale that a
 * dozen agents are editing in the same programme, and eleven insertions into it
 * would be a guaranteed merge conflict for zero behavioural gain. The resolver
 * has the same contract as `t(key, lang)` — unknown language falls back to
 * English, unknown key returns the key.
 *
 * Day and time-of-day labels are **not** duplicated here: `playIntent.today`,
 * `playIntent.tomorrow`, `playIntent.morning`, … already exist in
 * `utils/translations.ts` for all 11 bot languages and are reused verbatim.
 *
 * Placeholders are `{name}`-style (not `{{name}}`), matching `seriesT`.
 */

export type LiveCopyKey =
  // PRD 349 — follower push when a followed player's game goes live
  | 'live.followerTitle'
  | 'live.followerFallbackTitle'
  | 'live.followerBodyAtClub'
  | 'live.followerBody'
  | 'live.watchAction'
  // PRD 356 — /live
  | 'live.header'
  | 'live.startedMinutesAgo'
  | 'live.startedJustNow'
  | 'live.footer'
  | 'live.empty'
  | 'live.noCity'
  // PRD 356 — /play
  | 'play.askWhen'
  | 'play.askTime'
  | 'play.back'
  | 'play.confirmTitle'
  | 'play.confirmFooter'
  | 'play.openInApp'
  | 'play.cancel'
  | 'play.stopLooking'
  | 'play.stoppedLooking'
  | 'play.lookAgain'
  | 'play.needCity'
  | 'play.openProfile'
  | 'play.groupPost'
  | 'play.groupJoin'
  | 'play.groupOpenApp'
  | 'play.groupRateLimited'
  | 'play.groupJoined'
  | 'play.expired'
  // PRD 356 — bot command menu descriptions ("/" button)
  | 'play.menuDescription'
  | 'live.menuDescription'
  | 'menu.start'
  | 'menu.auth'
  | 'menu.login'
  | 'menu.my'
  | 'menu.games'
  // PRD 351 — /invite
  | 'menu.invite';

type LiveCopyBundle = Record<LiveCopyKey, string>;

const LIVE_COPY: Record<string, LiveCopyBundle> = {
  en: {
    'live.followerTitle': '{name} is playing live',
    'live.followerFallbackTitle': 'A friend is playing live',
    'live.followerBodyAtClub': '{sport} at {club} — watch the score now.',
    'live.followerBody': '{sport} in {city} — watch the score now.',
    'live.watchAction': 'Watch',
    'live.header': '🔴 Live now in {city}',
    'live.startedMinutesAgo': 'Started {minutes} min ago',
    'live.startedJustNow': 'Just started',
    'live.footer': 'Updated just now · /live to refresh',
    'live.empty': 'Nothing live right now. /games shows what’s coming up.',
    'live.noCity': 'Set your city in the app first.',
    'play.askWhen': 'When do you want to play? 🎾',
    'play.askTime': '{day} · what time?',
    'play.back': '← Back',
    'play.confirmTitle': '✅ You’re looking to play',
    'play.confirmFooter': 'We’ll message you when players or a game match.',
    'play.openInApp': 'Open in app',
    'play.cancel': 'Cancel',
    'play.stopLooking': 'Stop looking',
    'play.stoppedLooking': 'Stopped looking',
    'play.lookAgain': 'Look again',
    'play.needCity': 'Set your city in the app first.',
    'play.openProfile': 'Open profile',
    'play.groupPost': '🎾 {name} is looking to play {when} in {city}',
    'play.groupJoin': 'I’m in too',
    'play.groupOpenApp': 'Open app',
    'play.groupRateLimited': 'You already posted here recently. Try again later.',
    'play.groupJoined': 'You’re looking to play too — check your chat with the bot.',
    'play.expired': 'That request is no longer active.',
    'play.menuDescription': 'Say you want to play',
    'live.menuDescription': 'Games happening right now',
    'menu.start': 'Start and link your account',
    'menu.auth': 'Get a one-time login code',
    'menu.login': 'Get a login link',
    'menu.my': 'Your upcoming games',
    'menu.games': 'Games looking for players',
    'menu.invite': 'Get your invite link',
  },
  ru: {
    'live.followerTitle': '{name} играет прямо сейчас',
    'live.followerFallbackTitle': 'Ваш друг играет прямо сейчас',
    'live.followerBodyAtClub': '{sport} в «{club}» — смотрите счёт.',
    'live.followerBody': '{sport}, {city} — смотрите счёт.',
    'live.watchAction': 'Смотреть',
    'live.header': '🔴 Сейчас играют: {city}',
    'live.startedMinutesAgo': 'Начали {minutes} мин назад',
    'live.startedJustNow': 'Только что начали',
    'live.footer': 'Обновлено только что · /live — обновить',
    'live.empty': 'Сейчас ничего не идёт. Команда /games покажет ближайшие игры.',
    'live.noCity': 'Сначала укажите город в приложении.',
    'play.askWhen': 'Когда хотите поиграть? 🎾',
    'play.askTime': '{day} · во сколько?',
    'play.back': '← Назад',
    'play.confirmTitle': '✅ Вы ищете игру',
    'play.confirmFooter': 'Напишем, как только найдутся игроки или подходящая игра.',
    'play.openInApp': 'Открыть в приложении',
    'play.cancel': 'Отменить',
    'play.stopLooking': 'Больше не искать',
    'play.stoppedLooking': 'Поиск остановлен',
    'play.lookAgain': 'Искать снова',
    'play.needCity': 'Сначала укажите город в приложении.',
    'play.openProfile': 'Открыть профиль',
    'play.groupPost': '🎾 {name} ищет игру: {when}, {city}',
    'play.groupJoin': 'Я тоже',
    'play.groupOpenApp': 'Открыть приложение',
    'play.groupRateLimited': 'Вы недавно уже писали сюда. Попробуйте позже.',
    'play.groupJoined': 'Вы тоже ищете игру — загляните в чат с ботом.',
    'play.expired': 'Этот запрос уже неактивен.',
    'play.menuDescription': 'Сказать, что хотите поиграть',
    'live.menuDescription': 'Игры, которые идут сейчас',
    'menu.start': 'Начать и привязать аккаунт',
    'menu.auth': 'Получить одноразовый код входа',
    'menu.login': 'Получить ссылку для входа',
    'menu.my': 'Ваши ближайшие игры',
    'menu.games': 'Игры, куда ищут игроков',
    'menu.invite': 'Получить ссылку-приглашение',
  },
  sr: {
    'live.followerTitle': '{name} trenutno igra',
    'live.followerFallbackTitle': 'Prijatelj trenutno igra',
    'live.followerBodyAtClub': '{sport} u klubu {club} — pogledaj rezultat.',
    'live.followerBody': '{sport} u gradu {city} — pogledaj rezultat.',
    'live.watchAction': 'Gledaj',
    'live.header': '🔴 Uživo u gradu {city}',
    'live.startedMinutesAgo': 'Počelo pre {minutes} min',
    'live.startedJustNow': 'Upravo počelo',
    'live.footer': 'Ažurirano upravo sada · /live za osvežavanje',
    'live.empty': 'Trenutno ništa ne igra. /games prikazuje šta sledi.',
    'live.noCity': 'Prvo podesi grad u aplikaciji.',
    'play.askWhen': 'Kada želiš da igraš? 🎾',
    'play.askTime': '{day} · u koje vreme?',
    'play.back': '← Nazad',
    'play.confirmTitle': '✅ Tražiš igru',
    'play.confirmFooter': 'Javićemo ti čim se nađu igrači ili odgovarajuća igra.',
    'play.openInApp': 'Otvori u aplikaciji',
    'play.cancel': 'Otkaži',
    'play.stopLooking': 'Prestani da tražiš',
    'play.stoppedLooking': 'Pretraga zaustavljena',
    'play.lookAgain': 'Traži ponovo',
    'play.needCity': 'Prvo podesi grad u aplikaciji.',
    'play.openProfile': 'Otvori profil',
    'play.groupPost': '🎾 {name} traži igru {when} u gradu {city}',
    'play.groupJoin': 'I ja sam za',
    'play.groupOpenApp': 'Otvori aplikaciju',
    'play.groupRateLimited': 'Nedavno si već objavio ovde. Pokušaj kasnije.',
    'play.groupJoined': 'I ti tražiš igru — proveri poruke sa botom.',
    'play.expired': 'Ovaj zahtev više nije aktivan.',
    'play.menuDescription': 'Reci da želiš da igraš',
    'live.menuDescription': 'Igre koje traju upravo sada',
    'menu.start': 'Počni i poveži nalog',
    'menu.auth': 'Uzmi jednokratni kod za prijavu',
    'menu.login': 'Uzmi link za prijavu',
    'menu.my': 'Tvoje nadolazeće igre',
    'menu.games': 'Igre koje traže igrače',
    'menu.invite': 'Uzmi link za pozivnicu',
  },
  es: {
    'live.followerTitle': '{name} está jugando en directo',
    'live.followerFallbackTitle': 'Un amigo está jugando en directo',
    'live.followerBodyAtClub': '{sport} en {club}: mira el marcador.',
    'live.followerBody': '{sport} en {city}: mira el marcador.',
    'live.watchAction': 'Ver',
    'live.header': '🔴 En directo en {city}',
    'live.startedMinutesAgo': 'Empezó hace {minutes} min',
    'live.startedJustNow': 'Acaba de empezar',
    'live.footer': 'Actualizado ahora mismo · /live para refrescar',
    'live.empty': 'Ahora mismo no hay nada en directo. /games muestra lo que viene.',
    'live.noCity': 'Primero elige tu ciudad en la app.',
    'play.askWhen': '¿Cuándo quieres jugar? 🎾',
    'play.askTime': '{day} · ¿a qué hora?',
    'play.back': '← Atrás',
    'play.confirmTitle': '✅ Estás buscando partido',
    'play.confirmFooter': 'Te avisamos en cuanto haya jugadores o un partido que encaje.',
    'play.openInApp': 'Abrir en la app',
    'play.cancel': 'Cancelar',
    'play.stopLooking': 'Dejar de buscar',
    'play.stoppedLooking': 'Búsqueda detenida',
    'play.lookAgain': 'Buscar otra vez',
    'play.needCity': 'Primero elige tu ciudad en la app.',
    'play.openProfile': 'Abrir perfil',
    'play.groupPost': '🎾 {name} busca partido {when} en {city}',
    'play.groupJoin': 'Yo también',
    'play.groupOpenApp': 'Abrir app',
    'play.groupRateLimited': 'Ya has publicado aquí hace poco. Inténtalo más tarde.',
    'play.groupJoined': 'Tú también buscas partido: mira tu chat con el bot.',
    'play.expired': 'Esa solicitud ya no está activa.',
    'play.menuDescription': 'Di que quieres jugar',
    'live.menuDescription': 'Partidos que se juegan ahora',
    'menu.start': 'Empezar y vincular tu cuenta',
    'menu.auth': 'Obtener un código de acceso de un solo uso',
    'menu.login': 'Obtener un enlace de acceso',
    'menu.my': 'Tus próximos partidos',
    'menu.games': 'Partidos que buscan jugadores',
    'menu.invite': 'Consigue tu enlace de invitación',
  },
  cs: {
    'live.followerTitle': '{name} právě hraje',
    'live.followerFallbackTitle': 'Kamarád právě hraje',
    'live.followerBodyAtClub': '{sport} v klubu {club} — podívej se na skóre.',
    'live.followerBody': '{sport} ve městě {city} — podívej se na skóre.',
    'live.watchAction': 'Sledovat',
    'live.header': '🔴 Právě se hraje: {city}',
    'live.startedMinutesAgo': 'Začalo před {minutes} min',
    'live.startedJustNow': 'Právě začalo',
    'live.footer': 'Aktualizováno právě teď · /live pro obnovení',
    'live.empty': 'Teď se nic nehraje. /games ukáže, co se chystá.',
    'live.noCity': 'Nejdřív si v aplikaci nastav město.',
    'play.askWhen': 'Kdy si chceš zahrát? 🎾',
    'play.askTime': '{day} · v kolik?',
    'play.back': '← Zpět',
    'play.confirmTitle': '✅ Hledáš hru',
    'play.confirmFooter': 'Ozveme se, jakmile se najdou hráči nebo vhodná hra.',
    'play.openInApp': 'Otevřít v aplikaci',
    'play.cancel': 'Zrušit',
    'play.stopLooking': 'Přestat hledat',
    'play.stoppedLooking': 'Hledání zastaveno',
    'play.lookAgain': 'Hledat znovu',
    'play.needCity': 'Nejdřív si v aplikaci nastav město.',
    'play.openProfile': 'Otevřít profil',
    'play.groupPost': '🎾 {name} hledá hru {when} ve městě {city}',
    'play.groupJoin': 'Já taky',
    'play.groupOpenApp': 'Otevřít aplikaci',
    'play.groupRateLimited': 'Nedávno jsi tu už psal. Zkus to později.',
    'play.groupJoined': 'Taky hledáš hru — mrkni do chatu s botem.',
    'play.expired': 'Tento požadavek už není aktivní.',
    'play.menuDescription': 'Dej vědět, že si chceš zahrát',
    'live.menuDescription': 'Hry, které právě probíhají',
    'menu.start': 'Začít a propojit účet',
    'menu.auth': 'Získat jednorázový přihlašovací kód',
    'menu.login': 'Získat přihlašovací odkaz',
    'menu.my': 'Tvoje nadcházející hry',
    'menu.games': 'Hry, které hledají hráče',
    'menu.invite': 'Získej svůj odkaz na pozvánku',
  },
  ar: {
    'live.followerTitle': '{name} يلعب الآن',
    'live.followerFallbackTitle': 'صديق لك يلعب الآن',
    'live.followerBodyAtClub': '{sport} في {club} — تابع النتيجة.',
    'live.followerBody': '{sport} في {city} — تابع النتيجة.',
    'live.watchAction': 'شاهد',
    'live.header': '🔴 مباريات جارية الآن في {city}',
    'live.startedMinutesAgo': 'بدأت قبل {minutes} دقيقة',
    'live.startedJustNow': 'بدأت للتو',
    'live.footer': 'حُدِّثت للتو · اكتب /live للتحديث',
    'live.empty': 'لا توجد مباريات جارية الآن. اكتب /games لمعرفة القادم.',
    'live.noCity': 'حدِّد مدينتك في التطبيق أولاً.',
    'play.askWhen': 'متى تريد اللعب؟ 🎾',
    'play.askTime': '{day} · في أي وقت؟',
    // RTL: after bidi reordering a `←` sits at the visual right of the button
    // and still points left, which reads as "forward". Arabic's back arrow is `→`.
    'play.back': '→ رجوع',
    'play.confirmTitle': '✅ أنت تبحث عن مباراة',
    'play.confirmFooter': 'سنراسلك فور توفر لاعبين أو مباراة مناسبة.',
    'play.openInApp': 'افتح في التطبيق',
    'play.cancel': 'إلغاء',
    'play.stopLooking': 'إيقاف البحث',
    'play.stoppedLooking': 'تم إيقاف البحث',
    'play.lookAgain': 'ابحث من جديد',
    'play.needCity': 'حدِّد مدينتك في التطبيق أولاً.',
    'play.openProfile': 'افتح الملف الشخصي',
    'play.groupPost': '🎾 {name} يبحث عن مباراة {when} في {city}',
    'play.groupJoin': 'وأنا أيضاً',
    'play.groupOpenApp': 'افتح التطبيق',
    'play.groupRateLimited': 'لقد نشرت هنا قبل قليل. حاول لاحقاً.',
    'play.groupJoined': 'أنت أيضاً تبحث عن مباراة — راجع محادثتك مع البوت.',
    'play.expired': 'لم يعد هذا الطلب نشطاً.',
    'play.menuDescription': 'أخبرنا أنك تريد اللعب',
    'live.menuDescription': 'المباريات الجارية الآن',
    'menu.start': 'ابدأ واربط حسابك',
    'menu.auth': 'احصل على رمز دخول لمرة واحدة',
    'menu.login': 'احصل على رابط الدخول',
    'menu.my': 'مبارياتك القادمة',
    'menu.games': 'مباريات تبحث عن لاعبين',
    'menu.invite': 'احصل على رابط الدعوة',
  },
  zh: {
    'live.followerTitle': '{name} 正在比赛',
    'live.followerFallbackTitle': '你的好友正在比赛',
    'live.followerBodyAtClub': '{sport}，{club} — 查看实时比分。',
    'live.followerBody': '{sport}，{city} — 查看实时比分。',
    'live.watchAction': '观看',
    'live.header': '🔴 {city} 正在进行的比赛',
    'live.startedMinutesAgo': '已开始 {minutes} 分钟',
    'live.startedJustNow': '刚刚开始',
    'live.footer': '刚刚更新 · 发送 /live 刷新',
    'live.empty': '现在没有进行中的比赛。发送 /games 查看即将开始的比赛。',
    'live.noCity': '请先在应用中设置你的城市。',
    'play.askWhen': '你想什么时候打球？🎾',
    'play.askTime': '{day} · 什么时间？',
    'play.back': '← 返回',
    'play.confirmTitle': '✅ 你正在找球局',
    'play.confirmFooter': '找到球友或合适的球局后我们会通知你。',
    'play.openInApp': '在应用中打开',
    'play.cancel': '取消',
    'play.stopLooking': '停止寻找',
    'play.stoppedLooking': '已停止寻找',
    'play.lookAgain': '重新寻找',
    'play.needCity': '请先在应用中设置你的城市。',
    'play.openProfile': '打开个人资料',
    'play.groupPost': '🎾 {name} 想在 {city} 于{when}打球',
    'play.groupJoin': '我也来',
    'play.groupOpenApp': '打开应用',
    'play.groupRateLimited': '你刚刚已经发过了，请稍后再试。',
    'play.groupJoined': '你也在找球局了 — 请查看与机器人的聊天。',
    'play.expired': '该请求已失效。',
    'play.menuDescription': '告诉大家你想打球',
    'live.menuDescription': '正在进行的比赛',
    'menu.start': '开始并绑定账号',
    'menu.auth': '获取一次性登录验证码',
    'menu.login': '获取登录链接',
    'menu.my': '你即将进行的比赛',
    'menu.games': '正在找人的比赛',
    'menu.invite': '获取你的邀请链接',
  },
  id: {
    'live.followerTitle': '{name} sedang bermain',
    'live.followerFallbackTitle': 'Teman kamu sedang bermain',
    'live.followerBodyAtClub': '{sport} di {club} — lihat skornya.',
    'live.followerBody': '{sport} di {city} — lihat skornya.',
    'live.watchAction': 'Tonton',
    'live.header': '🔴 Sedang berlangsung di {city}',
    'live.startedMinutesAgo': 'Dimulai {minutes} menit lalu',
    'live.startedJustNow': 'Baru saja dimulai',
    'live.footer': 'Baru diperbarui · /live untuk menyegarkan',
    'live.empty': 'Belum ada yang berlangsung. /games menampilkan yang akan datang.',
    'live.noCity': 'Atur kotamu di aplikasi dulu.',
    'play.askWhen': 'Kapan kamu mau main? 🎾',
    'play.askTime': '{day} · jam berapa?',
    'play.back': '← Kembali',
    'play.confirmTitle': '✅ Kamu sedang mencari permainan',
    'play.confirmFooter': 'Kami kabari begitu ada pemain atau permainan yang cocok.',
    'play.openInApp': 'Buka di aplikasi',
    'play.cancel': 'Batalkan',
    'play.stopLooking': 'Berhenti mencari',
    'play.stoppedLooking': 'Pencarian dihentikan',
    'play.lookAgain': 'Cari lagi',
    'play.needCity': 'Atur kotamu di aplikasi dulu.',
    'play.openProfile': 'Buka profil',
    'play.groupPost': '🎾 {name} mencari permainan {when} di {city}',
    'play.groupJoin': 'Aku juga',
    'play.groupOpenApp': 'Buka aplikasi',
    'play.groupRateLimited': 'Kamu baru saja memposting di sini. Coba lagi nanti.',
    'play.groupJoined': 'Kamu juga sedang mencari permainan — cek chat dengan bot.',
    'play.expired': 'Permintaan itu sudah tidak aktif.',
    'play.menuDescription': 'Beri tahu kalau kamu mau main',
    'live.menuDescription': 'Permainan yang sedang berlangsung',
    'menu.start': 'Mulai dan tautkan akunmu',
    'menu.auth': 'Dapatkan kode masuk sekali pakai',
    'menu.login': 'Dapatkan tautan masuk',
    'menu.my': 'Permainanmu yang akan datang',
    'menu.games': 'Permainan yang mencari pemain',
    'menu.invite': 'Dapatkan tautan undanganmu',
  },
  hi: {
    'live.followerTitle': '{name} अभी खेल रहे हैं',
    'live.followerFallbackTitle': 'आपका एक दोस्त अभी खेल रहा है',
    'live.followerBodyAtClub': '{club} में {sport} — स्कोर देखें।',
    'live.followerBody': '{city} में {sport} — स्कोर देखें।',
    'live.watchAction': 'देखें',
    'live.header': '🔴 {city} में अभी चल रहे मैच',
    'live.startedMinutesAgo': '{minutes} मिनट पहले शुरू हुआ',
    'live.startedJustNow': 'अभी-अभी शुरू हुआ',
    'live.footer': 'अभी अपडेट हुआ · ताज़ा करने के लिए /live',
    'live.empty': 'अभी कुछ नहीं चल रहा। आगे क्या है यह /games दिखाएगा।',
    'live.noCity': 'पहले ऐप में अपना शहर चुनें।',
    'play.askWhen': 'आप कब खेलना चाहते हैं? 🎾',
    'play.askTime': '{day} · किस समय?',
    'play.back': '← वापस',
    'play.confirmTitle': '✅ आप खेल की तलाश में हैं',
    'play.confirmFooter': 'खिलाड़ी या उपयुक्त गेम मिलते ही हम आपको बताएंगे।',
    'play.openInApp': 'ऐप में खोलें',
    'play.cancel': 'रद्द करें',
    'play.stopLooking': 'तलाश बंद करें',
    'play.stoppedLooking': 'तलाश बंद कर दी गई',
    'play.lookAgain': 'फिर से तलाश करें',
    'play.needCity': 'पहले ऐप में अपना शहर चुनें।',
    'play.openProfile': 'प्रोफ़ाइल खोलें',
    'play.groupPost': '🎾 {name} {city} में {when} खेलना चाहते हैं',
    'play.groupJoin': 'मैं भी',
    'play.groupOpenApp': 'ऐप खोलें',
    'play.groupRateLimited': 'आपने हाल ही में यहाँ पोस्ट किया था। बाद में कोशिश करें।',
    'play.groupJoined': 'आप भी खेल की तलाश में हैं — बॉट के साथ चैट देखें।',
    'play.expired': 'यह अनुरोध अब सक्रिय नहीं है।',
    'play.menuDescription': 'बताएं कि आप खेलना चाहते हैं',
    'live.menuDescription': 'अभी चल रहे मैच',
    'menu.start': 'शुरू करें और अपना खाता जोड़ें',
    'menu.auth': 'एक बार का लॉगिन कोड लें',
    'menu.login': 'लॉगिन लिंक लें',
    'menu.my': 'आपके आगामी गेम',
    'menu.games': 'खिलाड़ी ढूंढ रहे गेम',
    'menu.invite': 'अपना आमंत्रण लिंक पाएँ',
  },
  th: {
    'live.followerTitle': '{name} กำลังเล่นอยู่ตอนนี้',
    'live.followerFallbackTitle': 'เพื่อนของคุณกำลังเล่นอยู่',
    'live.followerBodyAtClub': '{sport} ที่ {club} — ดูสกอร์เลย',
    'live.followerBody': '{sport} ที่ {city} — ดูสกอร์เลย',
    'live.watchAction': 'ดู',
    'live.header': '🔴 กำลังแข่งอยู่ใน {city}',
    'live.startedMinutesAgo': 'เริ่มไปแล้ว {minutes} นาที',
    'live.startedJustNow': 'เพิ่งเริ่ม',
    'live.footer': 'อัปเดตเมื่อสักครู่ · พิมพ์ /live เพื่อรีเฟรช',
    'live.empty': 'ตอนนี้ยังไม่มีแมตช์ที่กำลังแข่ง พิมพ์ /games เพื่อดูที่กำลังจะมาถึง',
    'live.noCity': 'ตั้งค่าเมืองของคุณในแอปก่อน',
    'play.askWhen': 'อยากเล่นเมื่อไหร่ 🎾',
    'play.askTime': '{day} · เวลาไหนดี',
    'play.back': '← ย้อนกลับ',
    'play.confirmTitle': '✅ คุณกำลังหาแมตช์อยู่',
    'play.confirmFooter': 'เราจะแจ้งทันทีที่มีผู้เล่นหรือแมตช์ที่เข้ากัน',
    'play.openInApp': 'เปิดในแอป',
    'play.cancel': 'ยกเลิก',
    'play.stopLooking': 'หยุดหา',
    'play.stoppedLooking': 'หยุดหาแล้ว',
    'play.lookAgain': 'หาอีกครั้ง',
    'play.needCity': 'ตั้งค่าเมืองของคุณในแอปก่อน',
    'play.openProfile': 'เปิดโปรไฟล์',
    'play.groupPost': '🎾 {name} กำลังหาแมตช์ {when} ที่ {city}',
    'play.groupJoin': 'ฉันด้วย',
    'play.groupOpenApp': 'เปิดแอป',
    'play.groupRateLimited': 'คุณเพิ่งโพสต์ที่นี่ไป ลองใหม่ภายหลัง',
    'play.groupJoined': 'คุณกำลังหาแมตช์ด้วยแล้ว — ดูแชทกับบอท',
    'play.expired': 'คำขอนี้ไม่ทำงานแล้ว',
    'play.menuDescription': 'บอกว่าคุณอยากเล่น',
    'live.menuDescription': 'แมตช์ที่กำลังแข่งตอนนี้',
    'menu.start': 'เริ่มต้นและเชื่อมบัญชีของคุณ',
    'menu.auth': 'ขอรหัสเข้าสู่ระบบแบบใช้ครั้งเดียว',
    'menu.login': 'ขอลิงก์เข้าสู่ระบบ',
    'menu.my': 'แมตช์ที่กำลังจะถึงของคุณ',
    'menu.games': 'แมตช์ที่กำลังหาผู้เล่น',
    'menu.invite': 'รับลิงก์ชวนเพื่อนของคุณ',
  },
  ja: {
    'live.followerTitle': '{name} さんがプレー中です',
    'live.followerFallbackTitle': '友だちがプレー中です',
    'live.followerBodyAtClub': '{club} で{sport} — スコアを見る。',
    'live.followerBody': '{city} で{sport} — スコアを見る。',
    'live.watchAction': '観る',
    'live.header': '🔴 {city} で進行中の試合',
    'live.startedMinutesAgo': '{minutes} 分前に開始',
    'live.startedJustNow': '始まったばかり',
    'live.footer': 'たった今更新 · /live で再読み込み',
    'live.empty': '今は進行中の試合はありません。/games で今後の予定を確認できます。',
    'live.noCity': '先にアプリで都市を設定してください。',
    'play.askWhen': 'いつプレーしますか？🎾',
    'play.askTime': '{day} · 何時ごろ？',
    'play.back': '← 戻る',
    'play.confirmTitle': '✅ 対戦相手を探しています',
    'play.confirmFooter': 'プレーヤーや条件に合う試合が見つかり次第お知らせします。',
    'play.openInApp': 'アプリで開く',
    'play.cancel': 'キャンセル',
    'play.stopLooking': '探すのをやめる',
    'play.stoppedLooking': '検索を停止しました',
    'play.lookAgain': 'もう一度探す',
    'play.needCity': '先にアプリで都市を設定してください。',
    'play.openProfile': 'プロフィールを開く',
    'play.groupPost': '🎾 {name} さんが {city} で{when}プレーする相手を探しています',
    'play.groupJoin': '私も参加',
    'play.groupOpenApp': 'アプリを開く',
    'play.groupRateLimited': 'つい先ほど投稿したばかりです。しばらくしてからお試しください。',
    'play.groupJoined': 'あなたも募集中です — ボットとのチャットを確認してください。',
    'play.expired': 'このリクエストはすでに無効です。',
    'play.menuDescription': 'プレーしたいと伝える',
    'live.menuDescription': '進行中の試合',
    'menu.start': '開始してアカウントを連携',
    'menu.auth': '使い捨てログインコードを取得',
    'menu.login': 'ログインリンクを取得',
    'menu.my': '今後の試合',
    'menu.games': 'プレーヤーを募集中の試合',
    'menu.invite': '招待リンクを取得',
  },
};

/** `t(key, lang)` for the live / play namespace. Unknown language falls back to `en`. */
export function liveT(
  key: LiveCopyKey,
  language: string | null | undefined,
  params: Record<string, string | number> = {},
): string {
  const lang = language && LIVE_COPY[language] ? language : 'en';
  const template = LIVE_COPY[lang][key] ?? LIVE_COPY.en[key] ?? key;
  return Object.entries(params).reduce(
    (acc, [name, value]) => acc.split(`{${name}}`).join(String(value)),
    template,
  );
}

export const LIVE_COPY_LANGUAGES = Object.keys(LIVE_COPY);
