/** Cap / web consumers of the deep-link catalog (#274 / #278) + assistant registry (#279). */
export {
  ANDROID_SHORTCUT_ACTION_IDS,
  BANDEJA_HTTPS_ORIGIN,
  DEEP_LINK_ACTIONS,
  DEEP_LINK_TEMPLATES,
  FIND_TODAY_PATH,
  FIND_TOMORROW_PATH,
  absoluteBandejaUrl,
  buildFindPath,
  buildGameChatPath,
  buildGameLivePath,
  buildGamePath,
  deepLinkActionPath,
  deepLinkActionUrl,
  deepLinkTemplatePath,
  deepLinkTemplateUrl,
  isFindTodayPath,
  resolveFindDeepLinkTarget,
  serializeDeepLinkCatalogMirror,
  type AndroidShortcutId,
  type DeepLinkActionId,
  type DeepLinkCatalogMirror,
  type DeepLinkTemplateId,
  type FindDeepLinkParams,
  type FindView,
} from './catalog';

export {
  ASSISTANT_FEATURE_ACTIONS,
  ASSISTANT_GAME_ENTITY_ACTIONS,
  IOS_APP_SHORTCUT_MAX,
  androidFeatureShortcutIds,
  assertAndroidFeatureShortcutParity,
  iosAppShortcutPriorityList,
  type AssistantFeatureAction,
  type AssistantFeatureActionId,
  type AssistantGameEntityAction,
  type AssistantGameEntityActionId,
  type AssistantLayer,
  type IosAppShortcutEntry,
} from './assistantRegistry';
