import type { AchievementDefinition, AchievementDefinitionId } from './types';

export const PODIUM_MIN_PLAYING_PARTICIPANTS = 8;

export const ACHIEVEMENT_CATALOG: readonly AchievementDefinition[] = [
  {
    id: 'podium_gold',
    rarity: 'LEGENDARY',
    artKey: 'podium_gold',
    ruleKind: 'PODIUM',
    titleKey: 'trophies.defs.podiumGold.title',
    descriptionKey: 'trophies.defs.podiumGold.description',
    place: 1,
    multiplicity: 'per_event',
  },
  {
    id: 'podium_silver',
    rarity: 'RARE',
    artKey: 'podium_silver',
    ruleKind: 'PODIUM',
    titleKey: 'trophies.defs.podiumSilver.title',
    descriptionKey: 'trophies.defs.podiumSilver.description',
    place: 2,
    multiplicity: 'per_event',
  },
  {
    id: 'podium_bronze',
    rarity: 'RARE',
    artKey: 'podium_bronze',
    ruleKind: 'PODIUM',
    titleKey: 'trophies.defs.podiumBronze.title',
    descriptionKey: 'trophies.defs.podiumBronze.description',
    place: 3,
    multiplicity: 'per_event',
  },
  {
    id: 'habit_first_win',
    rarity: 'COMMON',
    artKey: 'habit_first_win',
    ruleKind: 'HABIT_FIRST_WIN',
    titleKey: 'trophies.defs.firstWin.title',
    descriptionKey: 'trophies.defs.firstWin.description',
    threshold: 1,
    multiplicity: 'one_shot',
  },
  {
    id: 'habit_first_padel_game',
    rarity: 'COMMON',
    artKey: 'habit_first_padel_game',
    ruleKind: 'HABIT_SPORT_VOLUME',
    titleKey: 'trophies.defs.firstPadelGame.title',
    descriptionKey: 'trophies.defs.firstPadelGame.description',
    threshold: 1,
    sport: 'PADEL',
    multiplicity: 'one_shot',
  },
  {
    id: 'habit_wins_10',
    rarity: 'COMMON',
    artKey: 'habit_wins_10',
    ruleKind: 'HABIT_WINS',
    titleKey: 'trophies.defs.wins10.title',
    descriptionKey: 'trophies.defs.wins10.description',
    threshold: 10,
    multiplicity: 'one_shot',
  },
  {
    id: 'habit_wins_25',
    rarity: 'COMMON',
    artKey: 'habit_wins_25',
    ruleKind: 'HABIT_WINS',
    titleKey: 'trophies.defs.wins25.title',
    descriptionKey: 'trophies.defs.wins25.description',
    threshold: 25,
    multiplicity: 'one_shot',
  },
  {
    id: 'habit_wins_50',
    rarity: 'RARE',
    artKey: 'habit_wins_50',
    ruleKind: 'HABIT_WINS',
    titleKey: 'trophies.defs.wins50.title',
    descriptionKey: 'trophies.defs.wins50.description',
    threshold: 50,
    multiplicity: 'one_shot',
  },
  {
    id: 'habit_wins_100',
    rarity: 'RARE',
    artKey: 'habit_wins_100',
    ruleKind: 'HABIT_WINS',
    titleKey: 'trophies.defs.wins100.title',
    descriptionKey: 'trophies.defs.wins100.description',
    threshold: 100,
    multiplicity: 'one_shot',
  },
  {
    id: 'habit_wins_500',
    rarity: 'LEGENDARY',
    artKey: 'habit_wins_500',
    ruleKind: 'HABIT_WINS',
    titleKey: 'trophies.defs.wins500.title',
    descriptionKey: 'trophies.defs.wins500.description',
    threshold: 500,
    multiplicity: 'one_shot',
  },
  {
    id: 'habit_games_10',
    rarity: 'COMMON',
    artKey: 'habit_games_10',
    ruleKind: 'HABIT_VOLUME',
    titleKey: 'trophies.defs.games10.title',
    descriptionKey: 'trophies.defs.games10.description',
    threshold: 10,
    multiplicity: 'one_shot',
  },
  {
    id: 'habit_games_50',
    rarity: 'COMMON',
    artKey: 'habit_games_50',
    ruleKind: 'HABIT_VOLUME',
    titleKey: 'trophies.defs.games50.title',
    descriptionKey: 'trophies.defs.games50.description',
    threshold: 50,
    multiplicity: 'one_shot',
  },
  {
    id: 'habit_games_100',
    rarity: 'COMMON',
    artKey: 'habit_games_100',
    ruleKind: 'HABIT_VOLUME',
    titleKey: 'trophies.defs.games100.title',
    descriptionKey: 'trophies.defs.games100.description',
    threshold: 100,
    multiplicity: 'one_shot',
  },
  {
    id: 'habit_games_500',
    rarity: 'RARE',
    artKey: 'habit_games_500',
    ruleKind: 'HABIT_VOLUME',
    titleKey: 'trophies.defs.games500.title',
    descriptionKey: 'trophies.defs.games500.description',
    threshold: 500,
    multiplicity: 'one_shot',
  },
  {
    id: 'habit_games_1000',
    rarity: 'LEGENDARY',
    artKey: 'habit_games_1000',
    ruleKind: 'HABIT_VOLUME',
    titleKey: 'trophies.defs.games1000.title',
    descriptionKey: 'trophies.defs.games1000.description',
    threshold: 1000,
    multiplicity: 'one_shot',
  },
  {
    id: 'habit_streak_4',
    rarity: 'COMMON',
    artKey: 'habit_streak_4',
    ruleKind: 'HABIT_STREAK',
    titleKey: 'trophies.defs.streak4.title',
    descriptionKey: 'trophies.defs.streak4.description',
    threshold: 4,
    multiplicity: 'one_shot',
  },
  {
    id: 'habit_streak_8',
    rarity: 'RARE',
    artKey: 'habit_streak_8',
    ruleKind: 'HABIT_STREAK',
    titleKey: 'trophies.defs.streak8.title',
    descriptionKey: 'trophies.defs.streak8.description',
    threshold: 8,
    multiplicity: 'one_shot',
  },
  {
    id: 'habit_streak_12',
    rarity: 'RARE',
    artKey: 'habit_streak_12',
    ruleKind: 'HABIT_STREAK',
    titleKey: 'trophies.defs.streak12.title',
    descriptionKey: 'trophies.defs.streak12.description',
    threshold: 12,
    multiplicity: 'one_shot',
  },
  {
    id: 'habit_streak_16',
    rarity: 'RARE',
    artKey: 'habit_streak_16',
    ruleKind: 'HABIT_STREAK',
    titleKey: 'trophies.defs.streak16.title',
    descriptionKey: 'trophies.defs.streak16.description',
    threshold: 16,
    multiplicity: 'one_shot',
  },
  {
    id: 'habit_streak_32',
    rarity: 'RARE',
    artKey: 'habit_streak_32',
    ruleKind: 'HABIT_STREAK',
    titleKey: 'trophies.defs.streak32.title',
    descriptionKey: 'trophies.defs.streak32.description',
    threshold: 32,
    multiplicity: 'one_shot',
  },
  {
    id: 'habit_streak_64',
    rarity: 'LEGENDARY',
    artKey: 'habit_streak_64',
    ruleKind: 'HABIT_STREAK',
    titleKey: 'trophies.defs.streak64.title',
    descriptionKey: 'trophies.defs.streak64.description',
    threshold: 64,
    multiplicity: 'one_shot',
  },
  // Rally Starter — padel rated game organizing
  {
    id: 'habit_org_game_1',
    rarity: 'COMMON',
    artKey: 'habit_org_game_1',
    ruleKind: 'HABIT_ORGANIZE_GAME',
    titleKey: 'trophies.defs.orgGame1.title',
    descriptionKey: 'trophies.defs.orgGame1.description',
    threshold: 1,
    sport: 'PADEL',
    multiplicity: 'one_shot',
  },
  {
    id: 'habit_org_game_10',
    rarity: 'COMMON',
    artKey: 'habit_org_game_10',
    ruleKind: 'HABIT_ORGANIZE_GAME',
    titleKey: 'trophies.defs.orgGame10.title',
    descriptionKey: 'trophies.defs.orgGame10.description',
    threshold: 10,
    sport: 'PADEL',
    multiplicity: 'one_shot',
  },
  {
    id: 'habit_org_game_25',
    rarity: 'COMMON',
    artKey: 'habit_org_game_25',
    ruleKind: 'HABIT_ORGANIZE_GAME',
    titleKey: 'trophies.defs.orgGame25.title',
    descriptionKey: 'trophies.defs.orgGame25.description',
    threshold: 25,
    sport: 'PADEL',
    multiplicity: 'one_shot',
  },
  {
    id: 'habit_org_game_50',
    rarity: 'RARE',
    artKey: 'habit_org_game_50',
    ruleKind: 'HABIT_ORGANIZE_GAME',
    titleKey: 'trophies.defs.orgGame50.title',
    descriptionKey: 'trophies.defs.orgGame50.description',
    threshold: 50,
    sport: 'PADEL',
    multiplicity: 'one_shot',
  },
  {
    id: 'habit_org_game_100',
    rarity: 'RARE',
    artKey: 'habit_org_game_100',
    ruleKind: 'HABIT_ORGANIZE_GAME',
    titleKey: 'trophies.defs.orgGame100.title',
    descriptionKey: 'trophies.defs.orgGame100.description',
    threshold: 100,
    sport: 'PADEL',
    multiplicity: 'one_shot',
  },
  {
    id: 'habit_org_game_500',
    rarity: 'LEGENDARY',
    artKey: 'habit_org_game_500',
    ruleKind: 'HABIT_ORGANIZE_GAME',
    titleKey: 'trophies.defs.orgGame500.title',
    descriptionKey: 'trophies.defs.orgGame500.description',
    threshold: 500,
    sport: 'PADEL',
    multiplicity: 'one_shot',
  },
  // Padel tournament organizing
  {
    id: 'habit_org_tournament_1',
    rarity: 'COMMON',
    artKey: 'habit_org_tournament_1',
    ruleKind: 'HABIT_ORGANIZE_TOURNAMENT',
    titleKey: 'trophies.defs.orgTournament1.title',
    descriptionKey: 'trophies.defs.orgTournament1.description',
    threshold: 1,
    sport: 'PADEL',
    multiplicity: 'one_shot',
  },
  {
    id: 'habit_org_tournament_5',
    rarity: 'COMMON',
    artKey: 'habit_org_tournament_5',
    ruleKind: 'HABIT_ORGANIZE_TOURNAMENT',
    titleKey: 'trophies.defs.orgTournament5.title',
    descriptionKey: 'trophies.defs.orgTournament5.description',
    threshold: 5,
    sport: 'PADEL',
    multiplicity: 'one_shot',
  },
  {
    id: 'habit_org_tournament_10',
    rarity: 'COMMON',
    artKey: 'habit_org_tournament_10',
    ruleKind: 'HABIT_ORGANIZE_TOURNAMENT',
    titleKey: 'trophies.defs.orgTournament10.title',
    descriptionKey: 'trophies.defs.orgTournament10.description',
    threshold: 10,
    sport: 'PADEL',
    multiplicity: 'one_shot',
  },
  {
    id: 'habit_org_tournament_25',
    rarity: 'RARE',
    artKey: 'habit_org_tournament_25',
    ruleKind: 'HABIT_ORGANIZE_TOURNAMENT',
    titleKey: 'trophies.defs.orgTournament25.title',
    descriptionKey: 'trophies.defs.orgTournament25.description',
    threshold: 25,
    sport: 'PADEL',
    multiplicity: 'one_shot',
  },
  {
    id: 'habit_org_tournament_50',
    rarity: 'RARE',
    artKey: 'habit_org_tournament_50',
    ruleKind: 'HABIT_ORGANIZE_TOURNAMENT',
    titleKey: 'trophies.defs.orgTournament50.title',
    descriptionKey: 'trophies.defs.orgTournament50.description',
    threshold: 50,
    sport: 'PADEL',
    multiplicity: 'one_shot',
  },
  {
    id: 'habit_org_tournament_100',
    rarity: 'LEGENDARY',
    artKey: 'habit_org_tournament_100',
    ruleKind: 'HABIT_ORGANIZE_TOURNAMENT',
    titleKey: 'trophies.defs.orgTournament100.title',
    descriptionKey: 'trophies.defs.orgTournament100.description',
    threshold: 100,
    sport: 'PADEL',
    multiplicity: 'one_shot',
  },
  // Soul of the Party — BAR organizing (any sport)
  {
    id: 'habit_org_bar_1',
    rarity: 'COMMON',
    artKey: 'habit_org_bar_1',
    ruleKind: 'HABIT_ORGANIZE_BAR',
    titleKey: 'trophies.defs.orgBar1.title',
    descriptionKey: 'trophies.defs.orgBar1.description',
    threshold: 1,
    multiplicity: 'one_shot',
  },
  {
    id: 'habit_org_bar_5',
    rarity: 'COMMON',
    artKey: 'habit_org_bar_5',
    ruleKind: 'HABIT_ORGANIZE_BAR',
    titleKey: 'trophies.defs.orgBar5.title',
    descriptionKey: 'trophies.defs.orgBar5.description',
    threshold: 5,
    multiplicity: 'one_shot',
  },
  {
    id: 'habit_org_bar_10',
    rarity: 'COMMON',
    artKey: 'habit_org_bar_10',
    ruleKind: 'HABIT_ORGANIZE_BAR',
    titleKey: 'trophies.defs.orgBar10.title',
    descriptionKey: 'trophies.defs.orgBar10.description',
    threshold: 10,
    multiplicity: 'one_shot',
  },
  {
    id: 'habit_org_bar_25',
    rarity: 'RARE',
    artKey: 'habit_org_bar_25',
    ruleKind: 'HABIT_ORGANIZE_BAR',
    titleKey: 'trophies.defs.orgBar25.title',
    descriptionKey: 'trophies.defs.orgBar25.description',
    threshold: 25,
    multiplicity: 'one_shot',
  },
  {
    id: 'habit_org_bar_50',
    rarity: 'RARE',
    artKey: 'habit_org_bar_50',
    ruleKind: 'HABIT_ORGANIZE_BAR',
    titleKey: 'trophies.defs.orgBar50.title',
    descriptionKey: 'trophies.defs.orgBar50.description',
    threshold: 50,
    multiplicity: 'one_shot',
  },
  {
    id: 'habit_org_bar_100',
    rarity: 'LEGENDARY',
    artKey: 'habit_org_bar_100',
    ruleKind: 'HABIT_ORGANIZE_BAR',
    titleKey: 'trophies.defs.orgBar100.title',
    descriptionKey: 'trophies.defs.orgBar100.description',
    threshold: 100,
    multiplicity: 'one_shot',
  },
  // Giant Killer — upset wins vs higher-rated 2v2 teams (padel rated)
  {
    id: 'habit_giant_killer_1',
    rarity: 'COMMON',
    artKey: 'habit_giant_killer_1',
    ruleKind: 'HABIT_GIANT_KILLER',
    titleKey: 'trophies.defs.giantKiller1.title',
    descriptionKey: 'trophies.defs.giantKiller1.description',
    threshold: 1,
    sport: 'PADEL',
    multiplicity: 'one_shot',
  },
  {
    id: 'habit_giant_killer_5',
    rarity: 'COMMON',
    artKey: 'habit_giant_killer_5',
    ruleKind: 'HABIT_GIANT_KILLER',
    titleKey: 'trophies.defs.giantKiller5.title',
    descriptionKey: 'trophies.defs.giantKiller5.description',
    threshold: 5,
    sport: 'PADEL',
    multiplicity: 'one_shot',
  },
  {
    id: 'habit_giant_killer_10',
    rarity: 'RARE',
    artKey: 'habit_giant_killer_10',
    ruleKind: 'HABIT_GIANT_KILLER',
    titleKey: 'trophies.defs.giantKiller10.title',
    descriptionKey: 'trophies.defs.giantKiller10.description',
    threshold: 10,
    sport: 'PADEL',
    multiplicity: 'one_shot',
  },
  {
    id: 'habit_giant_killer_25',
    rarity: 'RARE',
    artKey: 'habit_giant_killer_25',
    ruleKind: 'HABIT_GIANT_KILLER',
    titleKey: 'trophies.defs.giantKiller25.title',
    descriptionKey: 'trophies.defs.giantKiller25.description',
    threshold: 25,
    sport: 'PADEL',
    multiplicity: 'one_shot',
  },
  {
    id: 'habit_giant_killer_50',
    rarity: 'LEGENDARY',
    artKey: 'habit_giant_killer_50',
    ruleKind: 'HABIT_GIANT_KILLER',
    titleKey: 'trophies.defs.giantKiller50.title',
    descriptionKey: 'trophies.defs.giantKiller50.description',
    threshold: 50,
    sport: 'PADEL',
    multiplicity: 'one_shot',
  },
  // Dynamic Duo — wins with the same partner
  {
    id: 'habit_dynamic_duo_10',
    rarity: 'COMMON',
    artKey: 'habit_dynamic_duo_10',
    ruleKind: 'HABIT_DYNAMIC_DUO',
    titleKey: 'trophies.defs.dynamicDuo10.title',
    descriptionKey: 'trophies.defs.dynamicDuo10.description',
    threshold: 10,
    sport: 'PADEL',
    multiplicity: 'one_shot',
  },
  {
    id: 'habit_dynamic_duo_50',
    rarity: 'RARE',
    artKey: 'habit_dynamic_duo_50',
    ruleKind: 'HABIT_DYNAMIC_DUO',
    titleKey: 'trophies.defs.dynamicDuo50.title',
    descriptionKey: 'trophies.defs.dynamicDuo50.description',
    threshold: 50,
    sport: 'PADEL',
    multiplicity: 'one_shot',
  },
  {
    id: 'habit_dynamic_duo_100',
    rarity: 'LEGENDARY',
    artKey: 'habit_dynamic_duo_100',
    ruleKind: 'HABIT_DYNAMIC_DUO',
    titleKey: 'trophies.defs.dynamicDuo100.title',
    descriptionKey: 'trophies.defs.dynamicDuo100.description',
    threshold: 100,
    sport: 'PADEL',
    multiplicity: 'one_shot',
  },
  // Open Court — distinct partners in qualifying doubles
  {
    id: 'habit_open_court_10',
    rarity: 'COMMON',
    artKey: 'habit_open_court_10',
    ruleKind: 'HABIT_OPEN_COURT',
    titleKey: 'trophies.defs.openCourt10.title',
    descriptionKey: 'trophies.defs.openCourt10.description',
    threshold: 10,
    sport: 'PADEL',
    multiplicity: 'one_shot',
  },
  {
    id: 'habit_open_court_25',
    rarity: 'COMMON',
    artKey: 'habit_open_court_25',
    ruleKind: 'HABIT_OPEN_COURT',
    titleKey: 'trophies.defs.openCourt25.title',
    descriptionKey: 'trophies.defs.openCourt25.description',
    threshold: 25,
    sport: 'PADEL',
    multiplicity: 'one_shot',
  },
  {
    id: 'habit_open_court_50',
    rarity: 'RARE',
    artKey: 'habit_open_court_50',
    ruleKind: 'HABIT_OPEN_COURT',
    titleKey: 'trophies.defs.openCourt50.title',
    descriptionKey: 'trophies.defs.openCourt50.description',
    threshold: 50,
    sport: 'PADEL',
    multiplicity: 'one_shot',
  },
  {
    id: 'habit_open_court_100',
    rarity: 'RARE',
    artKey: 'habit_open_court_100',
    ruleKind: 'HABIT_OPEN_COURT',
    titleKey: 'trophies.defs.openCourt100.title',
    descriptionKey: 'trophies.defs.openCourt100.description',
    threshold: 100,
    sport: 'PADEL',
    multiplicity: 'one_shot',
  },
  {
    id: 'habit_open_court_250',
    rarity: 'LEGENDARY',
    artKey: 'habit_open_court_250',
    ruleKind: 'HABIT_OPEN_COURT',
    titleKey: 'trophies.defs.openCourt250.title',
    descriptionKey: 'trophies.defs.openCourt250.description',
    threshold: 250,
    sport: 'PADEL',
    multiplicity: 'one_shot',
  },
] as const;

const BY_ID = new Map<AchievementDefinitionId, AchievementDefinition>(
  ACHIEVEMENT_CATALOG.map((d) => [d.id, d]),
);

export function getAchievementDefinition(
  id: string,
): AchievementDefinition | undefined {
  return BY_ID.get(id as AchievementDefinitionId);
}

export function isAchievementDefinitionId(id: string): id is AchievementDefinitionId {
  return BY_ID.has(id as AchievementDefinitionId);
}

export function podiumDefinitionForPlace(
  place: 1 | 2 | 3,
): AchievementDefinition {
  const found = ACHIEVEMENT_CATALOG.find((d) => d.ruleKind === 'PODIUM' && d.place === place);
  if (!found) throw new Error(`Missing podium definition for place ${place}`);
  return found;
}
