const COUNTRY_MAP: Record<string, { country: string; country_code: string }> = {
  Alemania: { country: 'Germany', country_code: 'DE' },
  Alimania: { country: 'Germany', country_code: 'DE' },
  Danmark: { country: 'Denmark', country_code: 'DK' },
  España: { country: 'Spain', country_code: 'ES' },
  Espana: { country: 'Spain', country_code: 'ES' },
  Espagne: { country: 'Spain', country_code: 'ES' },
  Espanha: { country: 'Spain', country_code: 'ES' },
  Espanya: { country: 'Spain', country_code: 'ES' },
  Spagna: { country: 'Spain', country_code: 'ES' },
  Österreich: { country: 'Austria', country_code: 'AT' },
  Osterreich: { country: 'Austria', country_code: 'AT' },
  Autriche: { country: 'Austria', country_code: 'AT' },
  Austria: { country: 'Austria', country_code: 'AT' },
  Turkey: { country: 'Turkey', country_code: 'TR' },
  Turquía: { country: 'Turkey', country_code: 'TR' },
  Turquia: { country: 'Turkey', country_code: 'TR' },
  Türkiye: { country: 'Turkey', country_code: 'TR' },
  Turkiye: { country: 'Turkey', country_code: 'TR' },

  Poland: { country: 'Poland', country_code: 'PL' },
  Polonia: { country: 'Poland', country_code: 'PL' },
  Polska: { country: 'Poland', country_code: 'PL' },
  Pologne: { country: 'Poland', country_code: 'PL' },
  Italia: { country: 'Italy', country_code: 'IT' },
  România: { country: 'Romania', country_code: 'RO' },
  Suiza: { country: 'Switzerland', country_code: 'CH' },
  Ελλάδα: { country: 'Greece', country_code: 'GR' },
  Κύπρος: { country: 'Cyprus', country_code: 'CY' },
  Кипр: { country: 'Cyprus', country_code: 'CY' },
  Lituania: { country: 'Lithuania', country_code: 'LT' },
  Lietuva: { country: 'Lithuania', country_code: 'LT' },
  Litauen: { country: 'Lithuania', country_code: 'LT' },
  Lithuania: { country: 'Lithuania', country_code: 'LT' },
  Letonia: { country: 'Latvia', country_code: 'LV' },
  Latvija: { country: 'Latvia', country_code: 'LV' },
  Lettland: { country: 'Latvia', country_code: 'LV' },
  Latvia: { country: 'Latvia', country_code: 'LV' },
  Eesti: { country: 'Estonia', country_code: 'EE' },
  Estonie: { country: 'Estonia', country_code: 'EE' },
  Estland: { country: 'Estonia', country_code: 'EE' },
  Estonia: { country: 'Estonia', country_code: 'EE' },
  Eslovenia: { country: 'Slovenia', country_code: 'SI' },
  Slovenija: { country: 'Slovenia', country_code: 'SI' },
  Slowenien: { country: 'Slovenia', country_code: 'SI' },
  Slovenia: { country: 'Slovenia', country_code: 'SI' },
  Eslovaquia: { country: 'Slovakia', country_code: 'SK' },
  Slovensko: { country: 'Slovakia', country_code: 'SK' },
  Slowakei: { country: 'Slovakia', country_code: 'SK' },
  Slovakia: { country: 'Slovakia', country_code: 'SK' },
  'Reino Unido': { country: 'United Kingdom', country_code: 'GB' },
  'Royaume-Uni': { country: 'United Kingdom', country_code: 'GB' },
  UK: { country: 'United Kingdom', country_code: 'GB' },
  'Great Britain': { country: 'United Kingdom', country_code: 'GB' },
  'Gran Bretaña': { country: 'United Kingdom', country_code: 'GB' },
  England: { country: 'United Kingdom', country_code: 'GB' },
  Scotland: { country: 'United Kingdom', country_code: 'GB' },
  Wales: { country: 'United Kingdom', country_code: 'GB' },
  Irlanda: { country: 'Ireland', country_code: 'IE' },
  Irlande: { country: 'Ireland', country_code: 'IE' },
  Ireland: { country: 'Ireland', country_code: 'IE' },
  Éire: { country: 'Ireland', country_code: 'IE' },
  Eire: { country: 'Ireland', country_code: 'IE' },
  Bulgaria: { country: 'Bulgaria', country_code: 'BG' },
  България: { country: 'Bulgaria', country_code: 'BG' },
  Bulgarie: { country: 'Bulgaria', country_code: 'BG' },
  Moldova: { country: 'Moldova', country_code: 'MD' },
  Moldavia: { country: 'Moldova', country_code: 'MD' },
  Moldavie: { country: 'Moldova', country_code: 'MD' },
  'Republic of Moldova': { country: 'Moldova', country_code: 'MD' },
  'Republica Moldova': { country: 'Moldova', country_code: 'MD' },
  Молдова: { country: 'Moldova', country_code: 'MD' },
  'North Macedonia': { country: 'North Macedonia', country_code: 'MK' },
  Macedonia: { country: 'North Macedonia', country_code: 'MK' },
  'Macedonia del Norte': { country: 'North Macedonia', country_code: 'MK' },
  'Norte de Macedonia': { country: 'North Macedonia', country_code: 'MK' },
  Македонија: { country: 'North Macedonia', country_code: 'MK' },
  'Северна Македонија': { country: 'North Macedonia', country_code: 'MK' },
};

export function normalizeCountry(
  rawCountry: string,
  rawCode?: string | null
): { country: string; country_code: string } {
  const trimmed = (rawCountry ?? '').trim();
  const entry = COUNTRY_MAP[trimmed];
  if (entry) return entry;
  const code = (rawCode ?? '').trim().toUpperCase();
  return {
    country: (trimmed || rawCountry) ?? '',
    country_code: code.length === 2 ? code : '',
  };
}
