const COUNTRY_MAP: Record<string, { country: string; country_code: string }> = {
  Alemania: { country: 'Germany', country_code: 'DE' },
  Alimania: { country: 'Germany', country_code: 'DE' },
  Danmark: { country: 'Denmark', country_code: 'DK' },
  España: { country: 'Spain', country_code: 'ES' },
  Espana: { country: 'Spain', country_code: 'ES' },
  Espagne: { country: 'Spain', country_code: 'ES' },
  Espanha: { country: 'Spain', country_code: 'ES' },
  Espanya: { country: 'Spain', country_code: 'ES' },
  Spagna: { country: 'Spain', country_code: 'ES' },
  Österreich: { country: 'Austria', country_code: 'AT' },
  Osterreich: { country: 'Austria', country_code: 'AT' },
  Autriche: { country: 'Austria', country_code: 'AT' },
  Austria: { country: 'Austria', country_code: 'AT' },
  Turkey: { country: 'Turkey', country_code: 'TR' },
  Turquía: { country: 'Turkey', country_code: 'TR' },
  Turquia: { country: 'Turkey', country_code: 'TR' },
  Türkiye: { country: 'Turkey', country_code: 'TR' },
  Turkiye: { country: 'Turkey', country_code: 'TR' },

  Poland: { country: 'Poland', country_code: 'PL' },
  Polonia: { country: 'Poland', country_code: 'PL' },
  Polska: { country: 'Poland', country_code: 'PL' },
  Pologne: { country: 'Poland', country_code: 'PL' },
  Italia: { country: 'Italy', country_code: 'IT' },
  România: { country: 'Romania', country_code: 'RO' },
  Suiza: { country: 'Switzerland', country_code: 'CH' },
  Ελλάδα: { country: 'Greece', country_code: 'GR' },
  Κύπρος: { country: 'Cyprus', country_code: 'CY' },
  Кипр: { country: 'Cyprus', country_code: 'CY' },
  Lituania: { country: 'Lithuania', country_code: 'LT' },
  Lietuva: { country: 'Lithuania', country_code: 'LT' },
  Litauen: { country: 'Lithuania', country_code: 'LT' },
  Lithuania: { country: 'Lithuania', country_code: 'LT' },
  Letonia: { country: 'Latvia', country_code: 'LV' },
  Latvija: { country: 'Latvia', country_code: 'LV' },
  Lettland: { country: 'Latvia', country_code: 'LV' },
  Latvia: { country: 'Latvia', country_code: 'LV' },
  Eesti: { country: 'Estonia', country_code: 'EE' },
  Estonie: { country: 'Estonia', country_code: 'EE' },
  Estland: { country: 'Estonia', country_code: 'EE' },
  Estonia: { country: 'Estonia', country_code: 'EE' },
  Eslovenia: { country: 'Slovenia', country_code: 'SI' },
  Slovenija: { country: 'Slovenia', country_code: 'SI' },
  Slowenien: { country: 'Slovenia', country_code: 'SI' },
  Slovenia: { country: 'Slovenia', country_code: 'SI' },
  Eslovaquia: { country: 'Slovakia', country_code: 'SK' },
  Slovensko: { country: 'Slovakia', country_code: 'SK' },
  Slowakei: { country: 'Slovakia', country_code: 'SK' },
  Slovakia: { country: 'Slovakia', country_code: 'SK' },
  'Reino Unido': { country: 'United Kingdom', country_code: 'GB' },
  'Royaume-Uni': { country: 'United Kingdom', country_code: 'GB' },
  UK: { country: 'United Kingdom', country_code: 'GB' },
  'Great Britain': { country: 'United Kingdom', country_code: 'GB' },
  'Gran Bretaña': { country: 'United Kingdom', country_code: 'GB' },
  England: { country: 'United Kingdom', country_code: 'GB' },
  Scotland: { country: 'United Kingdom', country_code: 'GB' },
  Wales: { country: 'United Kingdom', country_code: 'GB' },
  Irlanda: { country: 'Ireland', country_code: 'IE' },
  Irlande: { country: 'Ireland', country_code: 'IE' },
  Ireland: { country: 'Ireland', country_code: 'IE' },
  Éire: { country: 'Ireland', country_code: 'IE' },
  Eire: { country: 'Ireland', country_code: 'IE' },
  Israel: { country: 'Israel', country_code: 'IL' },
  Israël: { country: 'Israel', country_code: 'IL' },
  Израиль: { country: 'Israel', country_code: 'IL' },
  ישראל: { country: 'Israel', country_code: 'IL' },

  Bulgaria: { country: 'Bulgaria', country_code: 'BG' },
  България: { country: 'Bulgaria', country_code: 'BG' },
  Bulgarie: { country: 'Bulgaria', country_code: 'BG' },
  Moldova: { country: 'Moldova', country_code: 'MD' },
  Moldavia: { country: 'Moldova', country_code: 'MD' },
  Moldavie: { country: 'Moldova', country_code: 'MD' },
  'Republic of Moldova': { country: 'Moldova', country_code: 'MD' },
  'Republica Moldova': { country: 'Moldova', country_code: 'MD' },
  Молдова: { country: 'Moldova', country_code: 'MD' },
  'North Macedonia': { country: 'North Macedonia', country_code: 'MK' },
  Macedonia: { country: 'North Macedonia', country_code: 'MK' },
  'Macedonia del Norte': { country: 'North Macedonia', country_code: 'MK' },
  'Norte de Macedonia': { country: 'North Macedonia', country_code: 'MK' },
  Македонија: { country: 'North Macedonia', country_code: 'MK' },
  'Северна Македонија': { country: 'North Macedonia', country_code: 'MK' },
  'United Arab Emirates': { country: 'United Arab Emirates', country_code: 'AE' },
  UAE: { country: 'United Arab Emirates', country_code: 'AE' },
  'U.A.E.': { country: 'United Arab Emirates', country_code: 'AE' },
  'U.A.E': { country: 'United Arab Emirates', country_code: 'AE' },
  Emirates: { country: 'United Arab Emirates', country_code: 'AE' },
  'Arab Emirates': { country: 'United Arab Emirates', country_code: 'AE' },
  'Emiratos Árabes': { country: 'United Arab Emirates', country_code: 'AE' },
  'Emiratos Arabes': { country: 'United Arab Emirates', country_code: 'AE' },
  'Emiratos Árabes Unidos': { country: 'United Arab Emirates', country_code: 'AE' },
  'Emiratos Arabes Unidos': { country: 'United Arab Emirates', country_code: 'AE' },
  'Émirats arabes unis': { country: 'United Arab Emirates', country_code: 'AE' },
  'Vereinigte Arabische Emirate': { country: 'United Arab Emirates', country_code: 'AE' },
  'Emirados Árabes Unidos': { country: 'United Arab Emirates', country_code: 'AE' },
  'Emirados Arabes Unidos': { country: 'United Arab Emirates', country_code: 'AE' },
  'Förenade Arabemiraten': { country: 'United Arab Emirates', country_code: 'AE' },
  'Объединенные Арабские Эмираты': { country: 'United Arab Emirates', country_code: 'AE' },
  'الإمارات العربية المتحدة': { country: 'United Arab Emirates', country_code: 'AE' },
  Dubai: { country: 'United Arab Emirates', country_code: 'AE' },
  Kazakhstan: { country: 'Kazakhstan', country_code: 'KZ' },
  Kazajistán: { country: 'Kazakhstan', country_code: 'KZ' },
  Kazajistan: { country: 'Kazakhstan', country_code: 'KZ' },
  Kazahstan: { country: 'Kazakhstan', country_code: 'KZ' },
  Қазақстан: { country: 'Kazakhstan', country_code: 'KZ' },
  Ukraine: { country: 'Ukraine', country_code: 'UA' },
  Ucrania: { country: 'Ukraine', country_code: 'UA' },
  Ukraina: { country: 'Ukraine', country_code: 'UA' },
  Україна: { country: 'Ukraine', country_code: 'UA' },
  Украина: { country: 'Ukraine', country_code: 'UA' },
  Belarus: { country: 'Belarus', country_code: 'BY' },
  Bielorrusia: { country: 'Belarus', country_code: 'BY' },
  Belarusia: { country: 'Belarus', country_code: 'BY' },
  Беларусь: { country: 'Belarus', country_code: 'BY' },
  Белоруссия: { country: 'Belarus', country_code: 'BY' },
  Georgia: { country: 'Georgia', country_code: 'GE' },
  Georgien: { country: 'Georgia', country_code: 'GE' },
  Géorgie: { country: 'Georgia', country_code: 'GE' },
  საქართველო: { country: 'Georgia', country_code: 'GE' },
  Armenia: { country: 'Armenia', country_code: 'AM' },
  Armenien: { country: 'Armenia', country_code: 'AM' },
  Arménie: { country: 'Armenia', country_code: 'AM' },
  Հայաստան: { country: 'Armenia', country_code: 'AM' },

  Argentina: { country: 'Argentina', country_code: 'AR' },
  Bolivia: { country: 'Bolivia', country_code: 'BO' },
  Brazil: { country: 'Brazil', country_code: 'BR' },
  Brasil: { country: 'Brazil', country_code: 'BR' },
  Chile: { country: 'Chile', country_code: 'CL' },
  Colombia: { country: 'Colombia', country_code: 'CO' },
  Ecuador: { country: 'Ecuador', country_code: 'EC' },
  Guyana: { country: 'Guyana', country_code: 'GY' },
  Paraguay: { country: 'Paraguay', country_code: 'PY' },
  Peru: { country: 'Peru', country_code: 'PE' },
  Perú: { country: 'Peru', country_code: 'PE' },
  Suriname: { country: 'Suriname', country_code: 'SR' },
  Uruguay: { country: 'Uruguay', country_code: 'UY' },
  Venezuela: { country: 'Venezuela', country_code: 'VE' },
  'South Africa': { country: 'South Africa', country_code: 'ZA' },
  Sudáfrica: { country: 'South Africa', country_code: 'ZA' },
  Sudafrica: { country: 'South Africa', country_code: 'ZA' },
  'Afrique du Sud': { country: 'South Africa', country_code: 'ZA' },
  Südafrika: { country: 'South Africa', country_code: 'ZA' },
  SuidAfrika: { country: 'South Africa', country_code: 'ZA' },
  'Suid-Afrika': { country: 'South Africa', country_code: 'ZA' },
  'Saudi Arabia': { country: 'Saudi Arabia', country_code: 'SA' },
  'Arabia Saudí': { country: 'Saudi Arabia', country_code: 'SA' },
  'Arabia Saudi': { country: 'Saudi Arabia', country_code: 'SA' },
  'Arabia Saudita': { country: 'Saudi Arabia', country_code: 'SA' },
  'Kingdom of Saudi Arabia': { country: 'Saudi Arabia', country_code: 'SA' },
  KSA: { country: 'Saudi Arabia', country_code: 'SA' },
  السعودية: { country: 'Saudi Arabia', country_code: 'SA' },
  Oman: { country: 'Oman', country_code: 'OM' },
  Omán: { country: 'Oman', country_code: 'OM' },
  عمان: { country: 'Oman', country_code: 'OM' },
  Yemen: { country: 'Yemen', country_code: 'YE' },
  Yémen: { country: 'Yemen', country_code: 'YE' },
  اليمن: { country: 'Yemen', country_code: 'YE' },
};

export function normalizeCountry(
  rawCountry: string,
  rawCode?: string | null
): { country: string; country_code: string } {
  const trimmed = (rawCountry ?? '').trim();
  const entry = COUNTRY_MAP[trimmed];
  if (entry) return entry;
  const code = (rawCode ?? '').trim().toUpperCase();
  return {
    country: (trimmed || rawCountry) ?? '',
    country_code: code.length === 2 ? code : '',
  };
}
