-- AlterTable
ALTER TABLE "Game" ADD COLUMN     "pointsPerLoose" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "pointsPerTie" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "pointsPerWin" INTEGER NOT NULL DEFAULT 0;
