/**
 * Telegram AI assistant copy (docs/domains/agent.md § Telegram channel), all 11 bot
 * languages. Same contract as `liveT` / `seriesT`: unknown language → English, unknown key
 * → the key, `{name}` placeholders. Kept out of `utils/translations.ts` (see the note in
 * `services/live/liveCopy.ts`). Tool step labels are not here: they arrive already
 * localized in `tool.started.label` (`services/agent/i18n`).
 */

export const AGENT_BOT_COPY_KEYS = [
  'menu.ai',
  'button.open',
  'intro',
  'example.1',
  'example.2',
  'example.3',
  'status.sending',
  'status.queued',
  'status.thinking',
  'status.writing',
  'status.stopped',
  'status.interrupted',
  'error.generic',
  'error.timeout',
  'error.llm',
  'error.busy',
  'error.rateLimited',
  'error.budget',
  'error.budgetUntil',
  'error.textOnly',
  'error.tooLong',
  'error.notLinked',
  'answer.empty',
  'button.newChat',
  'button.chats',
  'button.stop',
  'button.exit',
  'button.confirm',
  'button.reject',
  'button.prev',
  'button.next',
  'newChat.started',
  'chats.title',
  'chats.empty',
  'chats.untitled',
  'chats.switched',
  'chats.you',
  'chats.assistant',
  'chats.noMessages',
  'exit.done',
  'action.expires',
  'action.confirmed',
  'action.rejected',
  'action.gone',
  'action.notAvailable',
  'toast.stopping',
  'toast.gone',
  'button.alwaysAllow',
  'button.permissions',
  'action.remembered',
  'action.autoApproved',
  'memory.saved',
  'action.cannotAlwaysAllow',
  'perm.title',
  'perm.hint',
  'perm.ask',
  'perm.always',
  'perm.locked',
  'perm.lockedAlert',
  'perm.empty',
  'perm.resetAll',
  'perm.resetConfirm',
  'perm.resetYes',
  'perm.back',
  'perm.resetDone',
  'perm.nowAlways',
  'perm.nowAsk',
  'booking.state.CONFIRMED',
  'booking.state.CANCELLED',
  'booking.state.PAST',
  'booking.state.UNKNOWN',
  'booking.cancellable',
  'entity.more',
  'button.openInApp',
  'button.connectedClubs',
  'action.clientOnly',
  'action.clientRequired',
  'action.unknown',
  'action.partial',
  'web.search',
  'web.searchCached',
  'web.unavailable',
  'web.read',
] as const;

export type AgentBotCopyKey = (typeof AGENT_BOT_COPY_KEYS)[number];

type Bundle = Record<AgentBotCopyKey, string>;

const EN: Bundle = {
  'menu.ai': 'AI assistant: ask about your games',
  'button.open': '🤖 AI assistant',
  intro:
    '🤖 <b>AI assistant</b>\nAsk about your games, leagues, clubs and players. Chats are shared with the app (My → AI).\n\nJust type your question, or try one:',
  'example.1': 'What games do I have this week?',
  'example.2': 'Find me a game tomorrow evening',
  'example.3': 'How is my league going?',
  'status.sending': '⏳ Sending…',
  'status.queued': '⏳ Queued (#{position})',
  'status.thinking': '🤔 Thinking…',
  'status.writing': '✍️ Writing…',
  'status.stopped': '⏹ Stopped.',
  'status.interrupted': '⚠️ The answer was interrupted. Please ask again.',
  'error.generic': '⚠️ Something went wrong. Please try again.',
  'error.timeout': '⚠️ That took too long. Please try again.',
  'error.llm': '⚠️ The assistant is unavailable right now. Please try later.',
  'error.busy': '⏳ I’m still answering in this chat. Wait a moment or press Stop.',
  'error.rateLimited': '⏳ Too many messages. Please wait a few minutes.',
  'error.budget': 'You’ve reached today’s assistant limit. Try again tomorrow.',
  'error.budgetUntil': 'You’ve reached today’s assistant limit. It resets at {time}.',
  'error.textOnly': 'I can only read text messages.',
  'error.tooLong': 'That message is too long (max {max} characters).',
  'error.notLinked': 'Link your Bandeja account first to use the assistant.',
  'answer.empty': '(no answer)',
  'button.newChat': '🆕 New chat',
  'button.chats': '💬 Chats',
  'button.stop': '⏹ Stop',
  'button.exit': '🚪 Exit',
  'button.confirm': '✅ Allow once',
  'button.reject': '✖ Reject',
  'button.prev': '◀',
  'button.next': '▶',
  'newChat.started': '🆕 New chat started. What can I help with?',
  'chats.title': '💬 Your chats ({page}/{pages}). Tap one to switch:',
  'chats.empty': 'No chats yet. Just type a question.',
  'chats.untitled': 'New chat',
  'chats.switched': '💬 Switched to “{title}”.',
  'chats.you': 'You',
  'chats.assistant': 'Assistant',
  'chats.noMessages': 'No messages yet. Type a question.',
  'exit.done': 'Assistant mode is off. Send /ai to come back.',
  'action.expires': 'Waiting for your confirmation.',
  'action.confirmed': '✅ Confirmed',
  'action.rejected': '✖ Cancelled',
  'action.gone': 'This action is no longer available.',
  'action.notAvailable': 'Confirming from Telegram isn’t available yet. Open the app (My → AI).',
  'toast.stopping': 'Stopping…',
  'toast.gone': 'No longer available',
  'button.alwaysAllow': '♾ Always allow',
  'button.permissions': '🔐 Permissions',
  'action.remembered': '♾ From now on “{tool}” runs without asking.',
  'action.autoApproved': '✅ Done automatically (you allowed “{tool}”).',
  'memory.saved': '🧠 Saved to memory: {description}. You can see or remove it in the app (AI → Assistant settings → Memory).',
  'action.cannotAlwaysAllow': 'This action always needs your confirmation. Tap “Allow once” instead.',
  'perm.title': 'Assistant permissions',
  'perm.hint': 'Tap a tool to switch between Ask and Always allow. Always allow only skips the tap: the assistant still checks your rights. 🔒 tools always ask.',
  'perm.ask': 'Ask',
  'perm.always': 'Always allow',
  'perm.locked': 'always asks',
  'perm.lockedAlert': '🔒 This tool always asks for confirmation.',
  'perm.empty': 'You have no assistant tools that change anything.',
  'perm.resetAll': '↺ Reset all',
  'perm.resetConfirm': 'Reset all tools to Ask?',
  'perm.resetYes': 'Yes, reset',
  'perm.back': '← Back',
  'perm.resetDone': 'All tools ask again',
  'perm.nowAlways': '♾ {tool}: always allow',
  'perm.nowAsk': '❔ {tool}: ask first',
  'booking.state.CONFIRMED': 'Confirmed',
  'booking.state.CANCELLED': 'Cancelled',
  'booking.state.PAST': 'Past',
  'booking.state.UNKNOWN': 'Status unknown',
  'booking.cancellable': 'can be cancelled',
  'entity.more': '…and {count} more',
  'button.openInApp': '📱 Open in app',
  'button.connectedClubs': '🔌 Connected clubs',
  'action.clientOnly': 'This change runs in the app: tap “Open in app” to confirm it there.',
  'action.clientRequired': 'Only the app can make this change. Open it to confirm.',
  'action.unknown': '⚠️ Result unknown — check Connected clubs',
  'action.partial': '⚠️ Partly done',
  'web.search': '🔎 Web search ({provider})',
  'web.searchCached': '🔎 Web search ({provider}, cached)',
  'web.unavailable': '🔎 Web search unavailable',
  'web.read': '📄 Read:',
};

const COPY: Record<string, Bundle> = {
  en: EN,
  ru: {
    'menu.ai': 'ИИ-ассистент: спросите о своих играх',
    'button.open': '🤖 ИИ-ассистент',
    intro:
      '🤖 <b>ИИ-ассистент</b>\nСпрашивайте о своих играх, лигах, клубах и игроках. Чаты общие с приложением (Мои → ИИ).\n\nПросто напишите вопрос или выберите пример:',
    'example.1': 'Какие у меня игры на этой неделе?',
    'example.2': 'Найди мне игру завтра вечером',
    'example.3': 'Как дела в моей лиге?',
    'status.sending': '⏳ Отправляю…',
    'status.queued': '⏳ В очереди (№{position})',
    'status.thinking': '🤔 Думаю…',
    'status.writing': '✍️ Пишу ответ…',
    'status.stopped': '⏹ Остановлено.',
    'status.interrupted': '⚠️ Ответ прервался. Спросите ещё раз.',
    'error.generic': '⚠️ Что-то пошло не так. Попробуйте ещё раз.',
    'error.timeout': '⚠️ Это заняло слишком много времени. Попробуйте ещё раз.',
    'error.llm': '⚠️ Ассистент сейчас недоступен. Попробуйте позже.',
    'error.busy': '⏳ Я ещё отвечаю в этом чате. Подождите или нажмите «Стоп».',
    'error.rateLimited': '⏳ Слишком много сообщений. Подождите несколько минут.',
    'error.budget': 'Дневной лимит ассистента исчерпан. Попробуйте завтра.',
    'error.budgetUntil': 'Дневной лимит ассистента исчерпан. Он обновится в {time}.',
    'error.textOnly': 'Я понимаю только текстовые сообщения.',
    'error.tooLong': 'Сообщение слишком длинное (максимум {max} символов).',
    'error.notLinked': 'Сначала привяжите аккаунт Bandeja, чтобы пользоваться ассистентом.',
    'answer.empty': '(нет ответа)',
    'button.newChat': '🆕 Новый чат',
    'button.chats': '💬 Чаты',
    'button.stop': '⏹ Стоп',
    'button.exit': '🚪 Выйти',
    'button.confirm': '✅ Разрешить один раз',
    'button.reject': '✖ Отклонить',
    'button.prev': '◀',
    'button.next': '▶',
    'newChat.started': '🆕 Новый чат. Чем помочь?',
    'chats.title': '💬 Ваши чаты ({page}/{pages}). Нажмите, чтобы переключиться:',
    'chats.empty': 'Чатов пока нет. Просто напишите вопрос.',
    'chats.untitled': 'Новый чат',
    'chats.switched': '💬 Переключено на «{title}».',
    'chats.you': 'Вы',
    'chats.assistant': 'Ассистент',
    'chats.noMessages': 'Сообщений пока нет. Напишите вопрос.',
    'exit.done': 'Режим ассистента выключен. Отправьте /ai, чтобы вернуться.',
    'action.expires': 'Ждёт вашего подтверждения.',
    'action.confirmed': '✅ Подтверждено',
    'action.rejected': '✖ Отменено',
    'action.gone': 'Это действие больше недоступно.',
    'action.notAvailable': 'Подтверждение из Telegram пока недоступно. Откройте приложение (Мои → ИИ).',
    'toast.stopping': 'Останавливаю…',
    'toast.gone': 'Больше недоступно',
    'button.alwaysAllow': '♾ Разрешать всегда',
    'button.permissions': '🔐 Разрешения',
    'action.remembered': '♾ Теперь «{tool}» выполняется без вопросов.',
    'action.autoApproved': '✅ Выполнено автоматически (вы разрешили «{tool}»).',
    'memory.saved': '🧠 Сохранено в память: {description}. Посмотреть или удалить можно в приложении (ИИ → Настройки ассистента → Память).',
    'action.cannotAlwaysAllow': 'Это действие всегда требует подтверждения. Нажмите «Разрешить один раз».',
    'perm.title': 'Разрешения ассистента',
    'perm.hint': 'Нажмите на инструмент, чтобы переключить «Спрашивать» и «Разрешать всегда». «Разрешать всегда» лишь пропускает нажатие: ассистент всё равно проверяет ваши права. 🔒 инструменты спрашивают всегда.',
    'perm.ask': 'Спрашивать',
    'perm.always': 'Разрешать всегда',
    'perm.locked': 'всегда спрашивает',
    'perm.lockedAlert': '🔒 Этот инструмент всегда спрашивает подтверждение.',
    'perm.empty': 'У вас нет инструментов ассистента, которые что-то меняют.',
    'perm.resetAll': '↺ Сбросить все',
    'perm.resetConfirm': 'Вернуть «Спрашивать» для всех инструментов?',
    'perm.resetYes': 'Да, сбросить',
    'perm.back': '← Назад',
    'perm.resetDone': 'Все инструменты снова спрашивают',
    'perm.nowAlways': '♾ {tool}: разрешать всегда',
    'perm.nowAsk': '❔ {tool}: спрашивать',
    'booking.state.CONFIRMED': 'Подтверждено',
    'booking.state.CANCELLED': 'Отменено',
    'booking.state.PAST': 'Прошло',
    'booking.state.UNKNOWN': 'Статус неизвестен',
    'booking.cancellable': 'можно отменить',
    'entity.more': '…и ещё {count}',
    'button.openInApp': '📱 Открыть в приложении',
    'button.connectedClubs': '🔌 Подключённые клубы',
    'action.clientOnly': 'Это изменение выполняется в приложении: нажмите «Открыть в приложении», чтобы подтвердить.',
    'action.clientRequired': 'Это изменение можно сделать только в приложении. Откройте его, чтобы подтвердить.',
    'action.unknown': '⚠️ Результат неизвестен — проверьте «Подключённые клубы»',
    'action.partial': '⚠️ Выполнено частично',
    'web.search': '🔎 Поиск в интернете ({provider})',
    'web.searchCached': '🔎 Поиск в интернете ({provider}, из кэша)',
    'web.unavailable': '🔎 Поиск в интернете недоступен',
    'web.read': '📄 Прочитано:',
  },
  sr: {
    'menu.ai': 'AI asistent: pitaj o svojim mečevima',
    'button.open': '🤖 AI asistent',
    intro:
      '🤖 <b>AI asistent</b>\nPitaj o svojim mečevima, ligama, klubovima i igračima. Četovi su zajednički sa aplikacijom (Moje → AI).\n\nSamo napiši pitanje ili izaberi primer:',
    'example.1': 'Koje mečeve imam ove nedelje?',
    'example.2': 'Nađi mi meč sutra uveče',
    'example.3': 'Kako ide moja liga?',
    'status.sending': '⏳ Šaljem…',
    'status.queued': '⏳ U redu (#{position})',
    'status.thinking': '🤔 Razmišljam…',
    'status.writing': '✍️ Pišem…',
    'status.stopped': '⏹ Zaustavljeno.',
    'status.interrupted': '⚠️ Odgovor je prekinut. Pitaj ponovo.',
    'error.generic': '⚠️ Nešto nije u redu. Pokušaj ponovo.',
    'error.timeout': '⚠️ Predugo je trajalo. Pokušaj ponovo.',
    'error.llm': '⚠️ Asistent trenutno nije dostupan. Pokušaj kasnije.',
    'error.busy': '⏳ Još odgovaram u ovom četu. Sačekaj ili pritisni Stop.',
    'error.rateLimited': '⏳ Previše poruka. Sačekaj nekoliko minuta.',
    'error.budget': 'Dostigao si dnevni limit asistenta. Pokušaj sutra.',
    'error.budgetUntil': 'Dostigao si dnevni limit asistenta. Obnavlja se u {time}.',
    'error.textOnly': 'Razumem samo tekstualne poruke.',
    'error.tooLong': 'Poruka je predugačka (najviše {max} karaktera).',
    'error.notLinked': 'Prvo poveži svoj Bandeja nalog da bi koristio asistenta.',
    'answer.empty': '(nema odgovora)',
    'button.newChat': '🆕 Novi čet',
    'button.chats': '💬 Četovi',
    'button.stop': '⏹ Stop',
    'button.exit': '🚪 Izađi',
    'button.confirm': '✅ Dozvoli jednom',
    'button.reject': '✖ Odbij',
    'button.prev': '◀',
    'button.next': '▶',
    'newChat.started': '🆕 Novi čet. Kako mogu da pomognem?',
    'chats.title': '💬 Tvoji četovi ({page}/{pages}). Dodirni za prebacivanje:',
    'chats.empty': 'Još nema četova. Samo napiši pitanje.',
    'chats.untitled': 'Novi čet',
    'chats.switched': '💬 Prebačeno na „{title}”.',
    'chats.you': 'Ti',
    'chats.assistant': 'Asistent',
    'chats.noMessages': 'Još nema poruka. Napiši pitanje.',
    'exit.done': 'Režim asistenta je isključen. Pošalji /ai za povratak.',
    'action.expires': 'Čeka tvoju potvrdu.',
    'action.confirmed': '✅ Potvrđeno',
    'action.rejected': '✖ Otkazano',
    'action.gone': 'Ova radnja više nije dostupna.',
    'action.notAvailable': 'Potvrda iz Telegrama još nije dostupna. Otvori aplikaciju (Moje → AI).',
    'toast.stopping': 'Zaustavljam…',
    'toast.gone': 'Više nije dostupno',
    'button.alwaysAllow': '♾ Uvek dozvoli',
    'button.permissions': '🔐 Dozvole',
    'action.remembered': '♾ Od sada se „{tool}” izvršava bez pitanja.',
    'action.autoApproved': '✅ Urađeno automatski (dozvolio si „{tool}”).',
    'memory.saved': '🧠 Sačuvano u memoriju: {description}. Možeš da ga vidiš ili ukloniš u aplikaciji (AI → Podešavanja asistenta → Memorija).',
    'action.cannotAlwaysAllow': 'Ova radnja uvek traži tvoju potvrdu. Dodirni „Dozvoli jednom”.',
    'perm.title': 'Dozvole asistenta',
    'perm.hint': 'Dodirni alat da prebaciš između „Pitaj” i „Uvek dozvoli”. „Uvek dozvoli” samo preskače dodir: asistent i dalje proverava tvoja prava. 🔒 alati uvek pitaju.',
    'perm.ask': 'Pitaj',
    'perm.always': 'Uvek dozvoli',
    'perm.locked': 'uvek pita',
    'perm.lockedAlert': '🔒 Ovaj alat uvek traži potvrdu.',
    'perm.empty': 'Nemaš alate asistenta koji nešto menjaju.',
    'perm.resetAll': '↺ Resetuj sve',
    'perm.resetConfirm': 'Vratiti sve alate na „Pitaj”?',
    'perm.resetYes': 'Da, resetuj',
    'perm.back': '← Nazad',
    'perm.resetDone': 'Svi alati ponovo pitaju',
    'perm.nowAlways': '♾ {tool}: uvek dozvoli',
    'perm.nowAsk': '❔ {tool}: pitaj',
    'booking.state.CONFIRMED': 'Potvrđeno',
    'booking.state.CANCELLED': 'Otkazano',
    'booking.state.PAST': 'Prošlo',
    'booking.state.UNKNOWN': 'Status nepoznat',
    'booking.cancellable': 'može se otkazati',
    'entity.more': '…i još {count}',
    'button.openInApp': '📱 Otvori u aplikaciji',
    'button.connectedClubs': '🔌 Povezani klubovi',
    'action.clientOnly': 'Ova izmena se radi u aplikaciji: dodirni „Otvori u aplikaciji” da je potvrdiš.',
    'action.clientRequired': 'Samo aplikacija može da napravi ovu izmenu. Otvori je da potvrdiš.',
    'action.unknown': '⚠️ Rezultat nepoznat — proveri Povezane klubove',
    'action.partial': '⚠️ Delimično urađeno',
    'web.search': '🔎 Pretraga interneta ({provider})',
    'web.searchCached': '🔎 Pretraga interneta ({provider}, iz keša)',
    'web.unavailable': '🔎 Pretraga interneta nije dostupna',
    'web.read': '📄 Pročitano:',
  },
  es: {
    'menu.ai': 'Asistente IA: pregunta por tus partidos',
    'button.open': '🤖 Asistente IA',
    intro:
      '🤖 <b>Asistente IA</b>\nPregunta por tus partidos, ligas, clubes y jugadores. Los chats se comparten con la app (Mis → IA).\n\nEscribe tu pregunta o prueba una:',
    'example.1': '¿Qué partidos tengo esta semana?',
    'example.2': 'Búscame un partido mañana por la tarde',
    'example.3': '¿Cómo va mi liga?',
    'status.sending': '⏳ Enviando…',
    'status.queued': '⏳ En cola (n.º {position})',
    'status.thinking': '🤔 Pensando…',
    'status.writing': '✍️ Escribiendo…',
    'status.stopped': '⏹ Detenido.',
    'status.interrupted': '⚠️ La respuesta se interrumpió. Vuelve a preguntar.',
    'error.generic': '⚠️ Algo salió mal. Inténtalo de nuevo.',
    'error.timeout': '⚠️ Tardó demasiado. Inténtalo de nuevo.',
    'error.llm': '⚠️ El asistente no está disponible ahora. Inténtalo más tarde.',
    'error.busy': '⏳ Todavía estoy respondiendo en este chat. Espera o pulsa Detener.',
    'error.rateLimited': '⏳ Demasiados mensajes. Espera unos minutos.',
    'error.budget': 'Has alcanzado el límite diario del asistente. Vuelve mañana.',
    'error.budgetUntil': 'Has alcanzado el límite diario del asistente. Se renueva: {time}.',
    'error.textOnly': 'Solo puedo leer mensajes de texto.',
    'error.tooLong': 'El mensaje es demasiado largo (máximo {max} caracteres).',
    'error.notLinked': 'Primero vincula tu cuenta de Bandeja para usar el asistente.',
    'answer.empty': '(sin respuesta)',
    'button.newChat': '🆕 Nuevo chat',
    'button.chats': '💬 Chats',
    'button.stop': '⏹ Detener',
    'button.exit': '🚪 Salir',
    'button.confirm': '✅ Permitir una vez',
    'button.reject': '✖ Rechazar',
    'button.prev': '◀',
    'button.next': '▶',
    'newChat.started': '🆕 Nuevo chat. ¿En qué te ayudo?',
    'chats.title': '💬 Tus chats ({page}/{pages}). Toca uno para cambiar:',
    'chats.empty': 'Aún no hay chats. Escribe una pregunta.',
    'chats.untitled': 'Nuevo chat',
    'chats.switched': '💬 Cambiado a «{title}».',
    'chats.you': 'Tú',
    'chats.assistant': 'Asistente',
    'chats.noMessages': 'Aún no hay mensajes. Escribe una pregunta.',
    'exit.done': 'Modo asistente desactivado. Envía /ai para volver.',
    'action.expires': 'Esperando tu confirmación.',
    'action.confirmed': '✅ Confirmado',
    'action.rejected': '✖ Cancelado',
    'action.gone': 'Esta acción ya no está disponible.',
    'action.notAvailable': 'Aún no se puede confirmar desde Telegram. Abre la app (Mis → IA).',
    'toast.stopping': 'Deteniendo…',
    'toast.gone': 'Ya no está disponible',
    'button.alwaysAllow': '♾ Permitir siempre',
    'button.permissions': '🔐 Permisos',
    'action.remembered': '♾ A partir de ahora «{tool}» se ejecuta sin preguntar.',
    'action.autoApproved': '✅ Hecho automáticamente (permitiste «{tool}»).',
    'memory.saved': '🧠 Guardado en la memoria: {description}. Puedes verlo o quitarlo en la app (IA → Ajustes del asistente → Memoria).',
    'action.cannotAlwaysAllow': 'Esta acción siempre necesita tu confirmación. Pulsa «Permitir una vez».',
    'perm.title': 'Permisos del asistente',
    'perm.hint': 'Toca una herramienta para cambiar entre Preguntar y Permitir siempre. Permitir siempre solo evita el toque: el asistente sigue comprobando tus permisos. Las herramientas 🔒 siempre preguntan.',
    'perm.ask': 'Preguntar',
    'perm.always': 'Permitir siempre',
    'perm.locked': 'siempre pregunta',
    'perm.lockedAlert': '🔒 Esta herramienta siempre pide confirmación.',
    'perm.empty': 'No tienes herramientas del asistente que cambien algo.',
    'perm.resetAll': '↺ Restablecer todo',
    'perm.resetConfirm': '¿Volver a Preguntar en todas las herramientas?',
    'perm.resetYes': 'Sí, restablecer',
    'perm.back': '← Atrás',
    'perm.resetDone': 'Todas las herramientas vuelven a preguntar',
    'perm.nowAlways': '♾ {tool}: permitir siempre',
    'perm.nowAsk': '❔ {tool}: preguntar',
    'booking.state.CONFIRMED': 'Confirmada',
    'booking.state.CANCELLED': 'Cancelada',
    'booking.state.PAST': 'Pasada',
    'booking.state.UNKNOWN': 'Estado desconocido',
    'booking.cancellable': 'se puede cancelar',
    'entity.more': '…y {count} más',
    'button.openInApp': '📱 Abrir en la app',
    'button.connectedClubs': '🔌 Clubes conectados',
    'action.clientOnly': 'Este cambio se hace en la app: toca «Abrir en la app» para confirmarlo allí.',
    'action.clientRequired': 'Solo la app puede hacer este cambio. Ábrela para confirmarlo.',
    'action.unknown': '⚠️ Resultado desconocido: revisa Clubes conectados',
    'action.partial': '⚠️ Hecho en parte',
    'web.search': '🔎 Búsqueda web ({provider})',
    'web.searchCached': '🔎 Búsqueda web ({provider}, en caché)',
    'web.unavailable': '🔎 Búsqueda web no disponible',
    'web.read': '📄 Leído:',
  },
  cs: {
    'menu.ai': 'AI asistent: zeptej se na své zápasy',
    'button.open': '🤖 AI asistent',
    intro:
      '🤖 <b>AI asistent</b>\nPtej se na své zápasy, ligy, kluby a hráče. Chaty se sdílejí s aplikací (Moje → AI).\n\nNapiš otázku nebo zkus příklad:',
    'example.1': 'Jaké zápasy mám tento týden?',
    'example.2': 'Najdi mi zápas zítra večer',
    'example.3': 'Jak se daří mé lize?',
    'status.sending': '⏳ Odesílám…',
    'status.queued': '⏳ Ve frontě (č. {position})',
    'status.thinking': '🤔 Přemýšlím…',
    'status.writing': '✍️ Píšu…',
    'status.stopped': '⏹ Zastaveno.',
    'status.interrupted': '⚠️ Odpověď byla přerušena. Zeptej se znovu.',
    'error.generic': '⚠️ Něco se pokazilo. Zkus to znovu.',
    'error.timeout': '⚠️ Trvalo to příliš dlouho. Zkus to znovu.',
    'error.llm': '⚠️ Asistent teď není dostupný. Zkus to později.',
    'error.busy': '⏳ V tomto chatu ještě odpovídám. Počkej nebo stiskni Stop.',
    'error.rateLimited': '⏳ Příliš mnoho zpráv. Počkej pár minut.',
    'error.budget': 'Dosáhl jsi denního limitu asistenta. Zkus to zítra.',
    'error.budgetUntil': 'Dosáhl jsi denního limitu asistenta. Obnoví se: {time}.',
    'error.textOnly': 'Umím číst jen textové zprávy.',
    'error.tooLong': 'Zpráva je příliš dlouhá (max. {max} znaků).',
    'error.notLinked': 'Nejdřív propoj svůj účet Bandeja, abys mohl asistenta používat.',
    'answer.empty': '(bez odpovědi)',
    'button.newChat': '🆕 Nový chat',
    'button.chats': '💬 Chaty',
    'button.stop': '⏹ Stop',
    'button.exit': '🚪 Ukončit',
    'button.confirm': '✅ Povolit jednou',
    'button.reject': '✖ Odmítnout',
    'button.prev': '◀',
    'button.next': '▶',
    'newChat.started': '🆕 Nový chat. S čím pomůžu?',
    'chats.title': '💬 Tvoje chaty ({page}/{pages}). Klepni pro přepnutí:',
    'chats.empty': 'Zatím žádné chaty. Napiš otázku.',
    'chats.untitled': 'Nový chat',
    'chats.switched': '💬 Přepnuto na „{title}“.',
    'chats.you': 'Ty',
    'chats.assistant': 'Asistent',
    'chats.noMessages': 'Zatím žádné zprávy. Napiš otázku.',
    'exit.done': 'Režim asistenta je vypnutý. Pošli /ai pro návrat.',
    'action.expires': 'Čeká na tvé potvrzení.',
    'action.confirmed': '✅ Potvrzeno',
    'action.rejected': '✖ Zrušeno',
    'action.gone': 'Tato akce už není dostupná.',
    'action.notAvailable': 'Potvrzení z Telegramu zatím není dostupné. Otevři aplikaci (Moje → AI).',
    'toast.stopping': 'Zastavuji…',
    'toast.gone': 'Už není dostupné',
    'button.alwaysAllow': '♾ Povolit vždy',
    'button.permissions': '🔐 Oprávnění',
    'action.remembered': '♾ Od teď se „{tool}“ provádí bez ptaní.',
    'action.autoApproved': '✅ Hotovo automaticky (povolil jsi „{tool}“).',
    'memory.saved': '🧠 Uloženo do paměti: {description}. Zobrazit nebo odebrat to můžeš v aplikaci (AI → Nastavení asistenta → Paměť).',
    'action.cannotAlwaysAllow': 'Tahle akce vždy vyžaduje tvé potvrzení. Klepni na „Povolit jednou“.',
    'perm.title': 'Oprávnění asistenta',
    'perm.hint': 'Klepnutím na nástroj přepneš mezi „Ptát se“ a „Povolit vždy“. „Povolit vždy“ jen přeskočí klepnutí: asistent dál kontroluje tvá práva. 🔒 nástroje se ptají vždy.',
    'perm.ask': 'Ptát se',
    'perm.always': 'Povolit vždy',
    'perm.locked': 'vždy se ptá',
    'perm.lockedAlert': '🔒 Tento nástroj vždy žádá o potvrzení.',
    'perm.empty': 'Nemáš žádné nástroje asistenta, které něco mění.',
    'perm.resetAll': '↺ Obnovit vše',
    'perm.resetConfirm': 'Vrátit všechny nástroje na „Ptát se“?',
    'perm.resetYes': 'Ano, obnovit',
    'perm.back': '← Zpět',
    'perm.resetDone': 'Všechny nástroje se znovu ptají',
    'perm.nowAlways': '♾ {tool}: povolit vždy',
    'perm.nowAsk': '❔ {tool}: ptát se',
    'booking.state.CONFIRMED': 'Potvrzeno',
    'booking.state.CANCELLED': 'Zrušeno',
    'booking.state.PAST': 'Proběhlo',
    'booking.state.UNKNOWN': 'Stav neznámý',
    'booking.cancellable': 'lze zrušit',
    'entity.more': '…a dalších {count}',
    'button.openInApp': '📱 Otevřít v aplikaci',
    'button.connectedClubs': '🔌 Připojené kluby',
    'action.clientOnly': 'Tato změna probíhá v aplikaci: klepni na „Otevřít v aplikaci“ a potvrď ji tam.',
    'action.clientRequired': 'Tuto změnu umí provést jen aplikace. Otevři ji a potvrď.',
    'action.unknown': '⚠️ Výsledek neznámý — zkontroluj Připojené kluby',
    'action.partial': '⚠️ Provedeno částečně',
    'web.search': '🔎 Hledání na webu ({provider})',
    'web.searchCached': '🔎 Hledání na webu ({provider}, z mezipaměti)',
    'web.unavailable': '🔎 Hledání na webu není dostupné',
    'web.read': '📄 Přečteno:',
  },
  ar: {
    'menu.ai': 'المساعد الذكي: اسأل عن مبارياتك',
    'button.open': '🤖 المساعد الذكي',
    intro:
      '🤖 <b>المساعد الذكي</b>\nاسأل عن مبارياتك ودورياتك والأندية واللاعبين. المحادثات مشتركة مع التطبيق (مبارياتي ← الذكاء الاصطناعي).\n\nاكتب سؤالك أو جرّب أحد الأمثلة:',
    'example.1': 'ما مبارياتي هذا الأسبوع؟',
    'example.2': 'ابحث لي عن مباراة مساء الغد',
    'example.3': 'كيف يسير دوريّ؟',
    'status.sending': '⏳ جارٍ الإرسال…',
    'status.queued': '⏳ في قائمة الانتظار (#{position})',
    'status.thinking': '🤔 أفكّر…',
    'status.writing': '✍️ أكتب…',
    'status.stopped': '⏹ تم الإيقاف.',
    'status.interrupted': '⚠️ انقطعت الإجابة. اسأل مرة أخرى.',
    'error.generic': '⚠️ حدث خطأ ما. حاول مرة أخرى.',
    'error.timeout': '⚠️ استغرق الأمر وقتًا طويلًا. حاول مرة أخرى.',
    'error.llm': '⚠️ المساعد غير متاح الآن. حاول لاحقًا.',
    'error.busy': '⏳ ما زلت أجيب في هذه المحادثة. انتظر قليلًا أو اضغط إيقاف.',
    'error.rateLimited': '⏳ رسائل كثيرة جدًا. انتظر بضع دقائق.',
    'error.budget': 'وصلت إلى الحد اليومي للمساعد. حاول غدًا.',
    'error.budgetUntil': 'وصلت إلى الحد اليومي للمساعد. يتجدد في {time}.',
    'error.textOnly': 'أستطيع قراءة الرسائل النصية فقط.',
    'error.tooLong': 'الرسالة طويلة جدًا (الحد الأقصى {max} حرف).',
    'error.notLinked': 'اربط حسابك في Bandeja أولًا لاستخدام المساعد.',
    'answer.empty': '(لا توجد إجابة)',
    'button.newChat': '🆕 محادثة جديدة',
    'button.chats': '💬 المحادثات',
    'button.stop': '⏹ إيقاف',
    'button.exit': '🚪 خروج',
    'button.confirm': '✅ السماح مرة واحدة',
    'button.reject': '✖ رفض',
    'button.prev': '◀',
    'button.next': '▶',
    'newChat.started': '🆕 محادثة جديدة. كيف أساعدك؟',
    'chats.title': '💬 محادثاتك ({page}/{pages}). اضغط للتبديل:',
    'chats.empty': 'لا توجد محادثات بعد. اكتب سؤالًا.',
    'chats.untitled': 'محادثة جديدة',
    'chats.switched': '💬 تم التبديل إلى «{title}».',
    'chats.you': 'أنت',
    'chats.assistant': 'المساعد',
    'chats.noMessages': 'لا توجد رسائل بعد. اكتب سؤالًا.',
    'exit.done': 'تم إيقاف وضع المساعد. أرسل /ai للعودة.',
    'action.expires': 'بانتظار تأكيدك.',
    'action.confirmed': '✅ تم التأكيد',
    'action.rejected': '✖ تم الإلغاء',
    'action.gone': 'هذا الإجراء لم يعد متاحًا.',
    'action.notAvailable': 'التأكيد من تيليجرام غير متاح بعد. افتح التطبيق (مبارياتي ← الذكاء الاصطناعي).',
    'toast.stopping': 'جارٍ الإيقاف…',
    'toast.gone': 'لم يعد متاحًا',
    'button.alwaysAllow': '♾ السماح دائمًا',
    'button.permissions': '🔐 الأذونات',
    'action.remembered': '♾ من الآن يُنفَّذ «{tool}» دون سؤال.',
    'action.autoApproved': '✅ تم تلقائيًا (سمحت بـ«{tool}»).',
    'memory.saved': '🧠 تم الحفظ في الذاكرة: {description}. يمكنك عرضها أو حذفها في التطبيق (الذكاء الاصطناعي ← إعدادات المساعد ← الذاكرة).',
    'action.cannotAlwaysAllow': 'هذا الإجراء يحتاج دائمًا إلى تأكيدك. اضغط «السماح مرة واحدة».',
    'perm.title': 'أذونات المساعد',
    'perm.hint': 'اضغط على أداة للتبديل بين «اسأل» و«السماح دائمًا». «السماح دائمًا» يتخطى الضغطة فقط: يظل المساعد يتحقق من صلاحياتك. أدوات 🔒 تسأل دائمًا.',
    'perm.ask': 'اسأل',
    'perm.always': 'السماح دائمًا',
    'perm.locked': 'تسأل دائمًا',
    'perm.lockedAlert': '🔒 هذه الأداة تطلب التأكيد دائمًا.',
    'perm.empty': 'ليست لديك أدوات مساعد تغيّر أي شيء.',
    'perm.resetAll': '↺ إعادة تعيين الكل',
    'perm.resetConfirm': 'إعادة كل الأدوات إلى «اسأل»؟',
    'perm.resetYes': 'نعم، أعد التعيين',
    'perm.back': '← رجوع',
    'perm.resetDone': 'كل الأدوات تسأل من جديد',
    'perm.nowAlways': '♾ {tool}: السماح دائمًا',
    'perm.nowAsk': '❔ {tool}: اسأل',
    'booking.state.CONFIRMED': 'مؤكد',
    'booking.state.CANCELLED': 'ملغى',
    'booking.state.PAST': 'منتهٍ',
    'booking.state.UNKNOWN': 'الحالة غير معروفة',
    'booking.cancellable': 'يمكن إلغاؤه',
    'entity.more': '…و{count} أخرى',
    'button.openInApp': '📱 افتح في التطبيق',
    'button.connectedClubs': '🔌 الأندية المتصلة',
    'action.clientOnly': 'يتم هذا التغيير في التطبيق: اضغط «افتح في التطبيق» لتأكيده هناك.',
    'action.clientRequired': 'التطبيق وحده يمكنه إجراء هذا التغيير. افتحه للتأكيد.',
    'action.unknown': '⚠️ النتيجة غير معروفة — راجع الأندية المتصلة',
    'action.partial': '⚠️ تم جزئيًا',
    'web.search': '🔎 بحث في الويب ({provider})',
    'web.searchCached': '🔎 بحث في الويب ({provider}، من الذاكرة المؤقتة)',
    'web.unavailable': '🔎 البحث في الويب غير متاح',
    'web.read': '📄 تمت القراءة:',
  },
  zh: {
    'menu.ai': 'AI 助手：询问你的比赛',
    'button.open': '🤖 AI 助手',
    intro:
      '🤖 <b>AI 助手</b>\n可以询问你的比赛、联赛、俱乐部和球员。对话与应用共享（我的 → AI）。\n\n直接输入问题，或试试这些：',
    'example.1': '我这周有哪些比赛？',
    'example.2': '帮我找一场明天晚上的比赛',
    'example.3': '我的联赛进展如何？',
    'status.sending': '⏳ 发送中…',
    'status.queued': '⏳ 排队中（第 {position} 位）',
    'status.thinking': '🤔 思考中…',
    'status.writing': '✍️ 正在撰写…',
    'status.stopped': '⏹ 已停止。',
    'status.interrupted': '⚠️ 回答被中断，请重新提问。',
    'error.generic': '⚠️ 出了点问题，请重试。',
    'error.timeout': '⚠️ 用时过长，请重试。',
    'error.llm': '⚠️ 助手暂时不可用，请稍后再试。',
    'error.busy': '⏳ 我还在回答这个对话，请稍等或点“停止”。',
    'error.rateLimited': '⏳ 消息过多，请等几分钟。',
    'error.budget': '今天的助手使用额度已用完，请明天再试。',
    'error.budgetUntil': '今天的助手使用额度已用完，将于 {time} 重置。',
    'error.textOnly': '我只能读取文字消息。',
    'error.tooLong': '消息太长（最多 {max} 个字符）。',
    'error.notLinked': '请先关联你的 Bandeja 账号再使用助手。',
    'answer.empty': '（无回答）',
    'button.newChat': '🆕 新对话',
    'button.chats': '💬 对话',
    'button.stop': '⏹ 停止',
    'button.exit': '🚪 退出',
    'button.confirm': '✅ 允许一次',
    'button.reject': '✖ 拒绝',
    'button.prev': '◀',
    'button.next': '▶',
    'newChat.started': '🆕 已开始新对话。需要什么帮助？',
    'chats.title': '💬 你的对话（{page}/{pages}），点按切换：',
    'chats.empty': '还没有对话。直接输入问题吧。',
    'chats.untitled': '新对话',
    'chats.switched': '💬 已切换到“{title}”。',
    'chats.you': '你',
    'chats.assistant': '助手',
    'chats.noMessages': '还没有消息。输入一个问题吧。',
    'exit.done': '已退出助手模式。发送 /ai 可返回。',
    'action.expires': '等待你的确认。',
    'action.confirmed': '✅ 已确认',
    'action.rejected': '✖ 已取消',
    'action.gone': '此操作已不可用。',
    'action.notAvailable': '暂不支持在 Telegram 中确认，请打开应用（我的 → AI）。',
    'toast.stopping': '正在停止…',
    'toast.gone': '已不可用',
    'button.alwaysAllow': '♾ 始终允许',
    'button.permissions': '🔐 权限',
    'action.remembered': '♾ 今后“{tool}”将直接执行，不再询问。',
    'action.autoApproved': '✅ 已自动完成（你允许了“{tool}”）。',
    'memory.saved': '🧠 已保存到记忆：{description}。可在应用中查看或删除（AI → 助手设置 → 记忆）。',
    'action.cannotAlwaysAllow': '此操作始终需要你确认。请点“允许一次”。',
    'perm.title': '助手权限',
    'perm.hint': '点击工具可在“询问”和“始终允许”之间切换。“始终允许”只省去点击：助手仍会检查你的权限。🔒 工具始终询问。',
    'perm.ask': '询问',
    'perm.always': '始终允许',
    'perm.locked': '始终询问',
    'perm.lockedAlert': '🔒 此工具始终需要确认。',
    'perm.empty': '你没有会做出更改的助手工具。',
    'perm.resetAll': '↺ 全部重置',
    'perm.resetConfirm': '将所有工具重置为“询问”？',
    'perm.resetYes': '是，重置',
    'perm.back': '← 返回',
    'perm.resetDone': '所有工具将重新询问',
    'perm.nowAlways': '♾ {tool}：始终允许',
    'perm.nowAsk': '❔ {tool}：询问',
    'booking.state.CONFIRMED': '已确认',
    'booking.state.CANCELLED': '已取消',
    'booking.state.PAST': '已结束',
    'booking.state.UNKNOWN': '状态未知',
    'booking.cancellable': '可取消',
    'entity.more': '…还有 {count} 个',
    'button.openInApp': '📱 在应用中打开',
    'button.connectedClubs': '🔌 已连接的俱乐部',
    'action.clientOnly': '此更改需在应用中执行：点击“在应用中打开”进行确认。',
    'action.clientRequired': '只有应用可以执行此更改，请打开应用确认。',
    'action.unknown': '⚠️ 结果未知——请检查已连接的俱乐部',
    'action.partial': '⚠️ 部分完成',
    'web.search': '🔎 网络搜索（{provider}）',
    'web.searchCached': '🔎 网络搜索（{provider}，缓存）',
    'web.unavailable': '🔎 网络搜索不可用',
    'web.read': '📄 已阅读：',
  },
  id: {
    'menu.ai': 'Asisten AI: tanya soal pertandinganmu',
    'button.open': '🤖 Asisten AI',
    intro:
      '🤖 <b>Asisten AI</b>\nTanyakan soal pertandingan, liga, klub, dan pemainmu. Obrolan dibagikan dengan aplikasi (Saya → AI).\n\nKetik pertanyaanmu atau coba salah satu:',
    'example.1': 'Pertandingan apa saja yang saya punya minggu ini?',
    'example.2': 'Carikan pertandingan besok malam',
    'example.3': 'Bagaimana perkembangan liga saya?',
    'status.sending': '⏳ Mengirim…',
    'status.queued': '⏳ Dalam antrean (#{position})',
    'status.thinking': '🤔 Berpikir…',
    'status.writing': '✍️ Menulis…',
    'status.stopped': '⏹ Dihentikan.',
    'status.interrupted': '⚠️ Jawaban terputus. Silakan tanya lagi.',
    'error.generic': '⚠️ Terjadi kesalahan. Coba lagi.',
    'error.timeout': '⚠️ Terlalu lama. Coba lagi.',
    'error.llm': '⚠️ Asisten sedang tidak tersedia. Coba nanti.',
    'error.busy': '⏳ Saya masih menjawab di obrolan ini. Tunggu sebentar atau tekan Berhenti.',
    'error.rateLimited': '⏳ Terlalu banyak pesan. Tunggu beberapa menit.',
    'error.budget': 'Batas harian asisten sudah tercapai. Coba lagi besok.',
    'error.budgetUntil': 'Batas harian asisten sudah tercapai. Direset pada {time}.',
    'error.textOnly': 'Saya hanya bisa membaca pesan teks.',
    'error.tooLong': 'Pesan terlalu panjang (maks. {max} karakter).',
    'error.notLinked': 'Tautkan akun Bandeja-mu dulu untuk memakai asisten.',
    'answer.empty': '(tidak ada jawaban)',
    'button.newChat': '🆕 Obrolan baru',
    'button.chats': '💬 Obrolan',
    'button.stop': '⏹ Berhenti',
    'button.exit': '🚪 Keluar',
    'button.confirm': '✅ Izinkan sekali',
    'button.reject': '✖ Tolak',
    'button.prev': '◀',
    'button.next': '▶',
    'newChat.started': '🆕 Obrolan baru dimulai. Ada yang bisa dibantu?',
    'chats.title': '💬 Obrolanmu ({page}/{pages}). Ketuk untuk beralih:',
    'chats.empty': 'Belum ada obrolan. Ketik saja pertanyaan.',
    'chats.untitled': 'Obrolan baru',
    'chats.switched': '💬 Beralih ke “{title}”.',
    'chats.you': 'Kamu',
    'chats.assistant': 'Asisten',
    'chats.noMessages': 'Belum ada pesan. Ketik pertanyaan.',
    'exit.done': 'Mode asisten nonaktif. Kirim /ai untuk kembali.',
    'action.expires': 'Menunggu konfirmasimu.',
    'action.confirmed': '✅ Dikonfirmasi',
    'action.rejected': '✖ Dibatalkan',
    'action.gone': 'Tindakan ini sudah tidak tersedia.',
    'action.notAvailable': 'Konfirmasi dari Telegram belum tersedia. Buka aplikasi (Saya → AI).',
    'toast.stopping': 'Menghentikan…',
    'toast.gone': 'Sudah tidak tersedia',
    'button.alwaysAllow': '♾ Selalu izinkan',
    'button.permissions': '🔐 Izin',
    'action.remembered': '♾ Mulai sekarang “{tool}” berjalan tanpa bertanya.',
    'action.autoApproved': '✅ Selesai otomatis (kamu mengizinkan “{tool}”).',
    'memory.saved': '🧠 Disimpan ke memori: {description}. Kamu bisa melihat atau menghapusnya di aplikasi (AI → Pengaturan asisten → Memori).',
    'action.cannotAlwaysAllow': 'Tindakan ini selalu butuh konfirmasimu. Ketuk “Izinkan sekali”.',
    'perm.title': 'Izin asisten',
    'perm.hint': 'Ketuk alat untuk beralih antara Tanya dan Selalu izinkan. Selalu izinkan hanya melewati ketukan: asisten tetap memeriksa hakmu. Alat 🔒 selalu bertanya.',
    'perm.ask': 'Tanya',
    'perm.always': 'Selalu izinkan',
    'perm.locked': 'selalu bertanya',
    'perm.lockedAlert': '🔒 Alat ini selalu meminta konfirmasi.',
    'perm.empty': 'Kamu tidak punya alat asisten yang mengubah sesuatu.',
    'perm.resetAll': '↺ Atur ulang semua',
    'perm.resetConfirm': 'Kembalikan semua alat ke Tanya?',
    'perm.resetYes': 'Ya, atur ulang',
    'perm.back': '← Kembali',
    'perm.resetDone': 'Semua alat bertanya lagi',
    'perm.nowAlways': '♾ {tool}: selalu izinkan',
    'perm.nowAsk': '❔ {tool}: tanya dulu',
    'booking.state.CONFIRMED': 'Dikonfirmasi',
    'booking.state.CANCELLED': 'Dibatalkan',
    'booking.state.PAST': 'Sudah lewat',
    'booking.state.UNKNOWN': 'Status tidak diketahui',
    'booking.cancellable': 'bisa dibatalkan',
    'entity.more': '…dan {count} lagi',
    'button.openInApp': '📱 Buka di aplikasi',
    'button.connectedClubs': '🔌 Klub terhubung',
    'action.clientOnly': 'Perubahan ini dijalankan di aplikasi: ketuk “Buka di aplikasi” untuk mengonfirmasinya.',
    'action.clientRequired': 'Hanya aplikasi yang bisa melakukan perubahan ini. Buka untuk mengonfirmasi.',
    'action.unknown': '⚠️ Hasil tidak diketahui — periksa Klub terhubung',
    'action.partial': '⚠️ Sebagian selesai',
    'web.search': '🔎 Pencarian web ({provider})',
    'web.searchCached': '🔎 Pencarian web ({provider}, dari cache)',
    'web.unavailable': '🔎 Pencarian web tidak tersedia',
    'web.read': '📄 Dibaca:',
  },
  hi: {
    'menu.ai': 'AI सहायक: अपने मैचों के बारे में पूछें',
    'button.open': '🤖 AI सहायक',
    intro:
      '🤖 <b>AI सहायक</b>\nअपने मैचों, लीग, क्लबों और खिलाड़ियों के बारे में पूछें। चैट ऐप के साथ साझा हैं (मेरे → AI)।\n\nअपना सवाल लिखें या कोई उदाहरण आज़माएँ:',
    'example.1': 'इस हफ़्ते मेरे कौन-से मैच हैं?',
    'example.2': 'कल शाम के लिए मेरे लिए कोई मैच ढूँढो',
    'example.3': 'मेरी लीग कैसी चल रही है?',
    'status.sending': '⏳ भेजा जा रहा है…',
    'status.queued': '⏳ कतार में (#{position})',
    'status.thinking': '🤔 सोच रहा हूँ…',
    'status.writing': '✍️ लिख रहा हूँ…',
    'status.stopped': '⏹ रोक दिया गया।',
    'status.interrupted': '⚠️ जवाब बीच में रुक गया। कृपया फिर से पूछें।',
    'error.generic': '⚠️ कुछ गलत हो गया। फिर से कोशिश करें।',
    'error.timeout': '⚠️ बहुत समय लग गया। फिर से कोशिश करें।',
    'error.llm': '⚠️ सहायक अभी उपलब्ध नहीं है। बाद में कोशिश करें।',
    'error.busy': '⏳ मैं इस चैट में अभी जवाब दे रहा हूँ। थोड़ा रुकें या रोकें दबाएँ।',
    'error.rateLimited': '⏳ बहुत ज़्यादा संदेश। कुछ मिनट रुकें।',
    'error.budget': 'आज की सहायक सीमा पूरी हो गई है। कल फिर कोशिश करें।',
    'error.budgetUntil': 'आज की सहायक सीमा पूरी हो गई है। यह {time} पर रीसेट होगी।',
    'error.textOnly': 'मैं सिर्फ़ टेक्स्ट संदेश पढ़ सकता हूँ।',
    'error.tooLong': 'संदेश बहुत लंबा है (अधिकतम {max} अक्षर)।',
    'error.notLinked': 'सहायक इस्तेमाल करने के लिए पहले अपना Bandeja खाता लिंक करें।',
    'answer.empty': '(कोई जवाब नहीं)',
    'button.newChat': '🆕 नई चैट',
    'button.chats': '💬 चैट',
    'button.stop': '⏹ रोकें',
    'button.exit': '🚪 बाहर निकलें',
    'button.confirm': '✅ एक बार अनुमति दें',
    'button.reject': '✖ अस्वीकार करें',
    'button.prev': '◀',
    'button.next': '▶',
    'newChat.started': '🆕 नई चैट शुरू हुई। मैं कैसे मदद करूँ?',
    'chats.title': '💬 आपकी चैट ({page}/{pages})। बदलने के लिए टैप करें:',
    'chats.empty': 'अभी कोई चैट नहीं। बस सवाल लिखें।',
    'chats.untitled': 'नई चैट',
    'chats.switched': '💬 “{title}” पर स्विच किया गया।',
    'chats.you': 'आप',
    'chats.assistant': 'सहायक',
    'chats.noMessages': 'अभी कोई संदेश नहीं। सवाल लिखें।',
    'exit.done': 'सहायक मोड बंद है। वापस आने के लिए /ai भेजें।',
    'action.expires': 'आपकी पुष्टि का इंतज़ार है।',
    'action.confirmed': '✅ पुष्टि हो गई',
    'action.rejected': '✖ रद्द किया गया',
    'action.gone': 'यह कार्रवाई अब उपलब्ध नहीं है।',
    'action.notAvailable': 'Telegram से पुष्टि अभी उपलब्ध नहीं है। ऐप खोलें (मेरे → AI)।',
    'toast.stopping': 'रोका जा रहा है…',
    'toast.gone': 'अब उपलब्ध नहीं',
    'button.alwaysAllow': '♾ हमेशा अनुमति दें',
    'button.permissions': '🔐 अनुमतियाँ',
    'action.remembered': '♾ अब से “{tool}” बिना पूछे चलेगा।',
    'action.autoApproved': '✅ अपने आप हो गया (आपने “{tool}” की अनुमति दी है)।',
    'memory.saved': '🧠 मेमोरी में सहेजा गया: {description}। इसे ऐप में देख या हटा सकते हैं (AI → सहायक सेटिंग्स → मेमोरी)।',
    'action.cannotAlwaysAllow': 'इस कार्रवाई के लिए हमेशा आपकी पुष्टि चाहिए। “एक बार अनुमति दें” दबाएँ।',
    'perm.title': 'असिस्टेंट की अनुमतियाँ',
    'perm.hint': 'किसी टूल पर टैप करके “पूछें” और “हमेशा अनुमति दें” के बीच बदलें। “हमेशा अनुमति दें” सिर्फ़ टैप छोड़ता है: असिस्टेंट फिर भी आपके अधिकार जाँचता है। 🔒 टूल हमेशा पूछते हैं।',
    'perm.ask': 'पूछें',
    'perm.always': 'हमेशा अनुमति दें',
    'perm.locked': 'हमेशा पूछता है',
    'perm.lockedAlert': '🔒 यह टूल हमेशा पुष्टि माँगता है।',
    'perm.empty': 'आपके पास कुछ बदलने वाले असिस्टेंट टूल नहीं हैं।',
    'perm.resetAll': '↺ सब रीसेट करें',
    'perm.resetConfirm': 'सभी टूल को “पूछें” पर वापस करें?',
    'perm.resetYes': 'हाँ, रीसेट करें',
    'perm.back': '← वापस',
    'perm.resetDone': 'सभी टूल फिर से पूछेंगे',
    'perm.nowAlways': '♾ {tool}: हमेशा अनुमति',
    'perm.nowAsk': '❔ {tool}: पहले पूछें',
    'booking.state.CONFIRMED': 'पुष्टि हुई',
    'booking.state.CANCELLED': 'रद्द',
    'booking.state.PAST': 'बीत चुकी',
    'booking.state.UNKNOWN': 'स्थिति अज्ञात',
    'booking.cancellable': 'रद्द की जा सकती है',
    'entity.more': '…और {count}',
    'button.openInApp': '📱 ऐप में खोलें',
    'button.connectedClubs': '🔌 जुड़े क्लब',
    'action.clientOnly': 'यह बदलाव ऐप में होता है: पुष्टि के लिए “ऐप में खोलें” पर टैप करें।',
    'action.clientRequired': 'यह बदलाव केवल ऐप कर सकता है। पुष्टि के लिए ऐप खोलें।',
    'action.unknown': '⚠️ परिणाम अज्ञात — जुड़े क्लब देखें',
    'action.partial': '⚠️ आंशिक रूप से पूरा',
    'web.search': '🔎 वेब खोज ({provider})',
    'web.searchCached': '🔎 वेब खोज ({provider}, कैश से)',
    'web.unavailable': '🔎 वेब खोज उपलब्ध नहीं',
    'web.read': '📄 पढ़ा गया:',
  },
  th: {
    'menu.ai': 'ผู้ช่วย AI: ถามเรื่องเกมของคุณ',
    'button.open': '🤖 ผู้ช่วย AI',
    intro:
      '🤖 <b>ผู้ช่วย AI</b>\nถามเรื่องเกม ลีก คลับ และผู้เล่นของคุณได้ แชทใช้ร่วมกับแอป (ของฉัน → AI)\n\nพิมพ์คำถามได้เลย หรือลองตัวอย่าง:',
    'example.1': 'สัปดาห์นี้ฉันมีเกมอะไรบ้าง?',
    'example.2': 'หาเกมให้ฉันพรุ่งนี้ตอนเย็น',
    'example.3': 'ลีกของฉันเป็นอย่างไรบ้าง?',
    'status.sending': '⏳ กำลังส่ง…',
    'status.queued': '⏳ อยู่ในคิว (#{position})',
    'status.thinking': '🤔 กำลังคิด…',
    'status.writing': '✍️ กำลังเขียน…',
    'status.stopped': '⏹ หยุดแล้ว',
    'status.interrupted': '⚠️ คำตอบถูกขัดจังหวะ กรุณาถามอีกครั้ง',
    'error.generic': '⚠️ มีบางอย่างผิดพลาด ลองอีกครั้ง',
    'error.timeout': '⚠️ ใช้เวลานานเกินไป ลองอีกครั้ง',
    'error.llm': '⚠️ ผู้ช่วยไม่พร้อมใช้งานตอนนี้ ลองใหม่ภายหลัง',
    'error.busy': '⏳ ฉันยังตอบในแชทนี้อยู่ รอสักครู่หรือกดหยุด',
    'error.rateLimited': '⏳ ส่งข้อความมากเกินไป รอสักครู่',
    'error.budget': 'ใช้ผู้ช่วยครบโควตาวันนี้แล้ว ลองใหม่พรุ่งนี้',
    'error.budgetUntil': 'ใช้ผู้ช่วยครบโควตาวันนี้แล้ว จะรีเซ็ตเวลา {time}',
    'error.textOnly': 'ฉันอ่านได้เฉพาะข้อความตัวอักษร',
    'error.tooLong': 'ข้อความยาวเกินไป (สูงสุด {max} ตัวอักษร)',
    'error.notLinked': 'เชื่อมบัญชี Bandeja ก่อนเพื่อใช้ผู้ช่วย',
    'answer.empty': '(ไม่มีคำตอบ)',
    'button.newChat': '🆕 แชทใหม่',
    'button.chats': '💬 แชท',
    'button.stop': '⏹ หยุด',
    'button.exit': '🚪 ออก',
    'button.confirm': '✅ อนุญาตครั้งเดียว',
    'button.reject': '✖ ปฏิเสธ',
    'button.prev': '◀',
    'button.next': '▶',
    'newChat.started': '🆕 เริ่มแชทใหม่แล้ว ให้ช่วยอะไรดี?',
    'chats.title': '💬 แชทของคุณ ({page}/{pages}) แตะเพื่อสลับ:',
    'chats.empty': 'ยังไม่มีแชท พิมพ์คำถามได้เลย',
    'chats.untitled': 'แชทใหม่',
    'chats.switched': '💬 สลับไปที่ “{title}” แล้ว',
    'chats.you': 'คุณ',
    'chats.assistant': 'ผู้ช่วย',
    'chats.noMessages': 'ยังไม่มีข้อความ พิมพ์คำถามได้เลย',
    'exit.done': 'ปิดโหมดผู้ช่วยแล้ว ส่ง /ai เพื่อกลับมา',
    'action.expires': 'รอการยืนยันจากคุณ',
    'action.confirmed': '✅ ยืนยันแล้ว',
    'action.rejected': '✖ ยกเลิกแล้ว',
    'action.gone': 'การดำเนินการนี้ไม่พร้อมใช้งานแล้ว',
    'action.notAvailable': 'ยังยืนยันจาก Telegram ไม่ได้ เปิดแอป (ของฉัน → AI)',
    'toast.stopping': 'กำลังหยุด…',
    'toast.gone': 'ไม่พร้อมใช้งานแล้ว',
    'button.alwaysAllow': '♾ อนุญาตเสมอ',
    'button.permissions': '🔐 สิทธิ์',
    'action.remembered': '♾ ต่อจากนี้ “{tool}” จะทำงานโดยไม่ถาม',
    'action.autoApproved': '✅ ทำให้อัตโนมัติแล้ว (คุณอนุญาต “{tool}”)',
    'memory.saved': '🧠 บันทึกลงความจำแล้ว: {description} ดูหรือลบได้ในแอป (AI → การตั้งค่าผู้ช่วย → ความจำ)',
    'action.cannotAlwaysAllow': 'การกระทำนี้ต้องให้คุณยืนยันทุกครั้ง แตะ “อนุญาตครั้งเดียว” แทน',
    'perm.title': 'สิทธิ์ของผู้ช่วย',
    'perm.hint': 'แตะเครื่องมือเพื่อสลับระหว่าง “ถามก่อน” และ “อนุญาตเสมอ” “อนุญาตเสมอ” แค่ข้ามการแตะ ผู้ช่วยยังตรวจสิทธิ์ของคุณเสมอ เครื่องมือ 🔒 จะถามทุกครั้ง',
    'perm.ask': 'ถามก่อน',
    'perm.always': 'อนุญาตเสมอ',
    'perm.locked': 'ถามทุกครั้ง',
    'perm.lockedAlert': '🔒 เครื่องมือนี้ขอการยืนยันทุกครั้ง',
    'perm.empty': 'คุณไม่มีเครื่องมือผู้ช่วยที่เปลี่ยนแปลงข้อมูล',
    'perm.resetAll': '↺ รีเซ็ตทั้งหมด',
    'perm.resetConfirm': 'ตั้งเครื่องมือทั้งหมดกลับเป็น “ถามก่อน” ไหม?',
    'perm.resetYes': 'ใช่ รีเซ็ต',
    'perm.back': '← กลับ',
    'perm.resetDone': 'เครื่องมือทั้งหมดจะถามอีกครั้ง',
    'perm.nowAlways': '♾ {tool}: อนุญาตเสมอ',
    'perm.nowAsk': '❔ {tool}: ถามก่อน',
    'booking.state.CONFIRMED': 'ยืนยันแล้ว',
    'booking.state.CANCELLED': 'ยกเลิกแล้ว',
    'booking.state.PAST': 'ผ่านไปแล้ว',
    'booking.state.UNKNOWN': 'ไม่ทราบสถานะ',
    'booking.cancellable': 'ยกเลิกได้',
    'entity.more': '…และอีก {count} รายการ',
    'button.openInApp': '📱 เปิดในแอป',
    'button.connectedClubs': '🔌 คลับที่เชื่อมต่อ',
    'action.clientOnly': 'การเปลี่ยนแปลงนี้ทำในแอป: แตะ “เปิดในแอป” เพื่อยืนยัน',
    'action.clientRequired': 'มีเพียงแอปที่ทำการเปลี่ยนแปลงนี้ได้ เปิดแอปเพื่อยืนยัน',
    'action.unknown': '⚠️ ไม่ทราบผลลัพธ์ — ตรวจสอบคลับที่เชื่อมต่อ',
    'action.partial': '⚠️ ทำได้บางส่วน',
    'web.search': '🔎 ค้นหาบนเว็บ ({provider})',
    'web.searchCached': '🔎 ค้นหาบนเว็บ ({provider}, จากแคช)',
    'web.unavailable': '🔎 การค้นหาเว็บไม่พร้อมใช้งาน',
    'web.read': '📄 อ่านแล้ว:',
  },
  ja: {
    'menu.ai': 'AIアシスタント：試合について質問',
    'button.open': '🤖 AIアシスタント',
    intro:
      '🤖 <b>AIアシスタント</b>\n試合、リーグ、クラブ、プレーヤーについて質問できます。チャットはアプリと共有されます（マイ → AI）。\n\n質問を入力するか、例を試してください：',
    'example.1': '今週の試合は？',
    'example.2': '明日の夜の試合を探して',
    'example.3': '私のリーグの状況は？',
    'status.sending': '⏳ 送信中…',
    'status.queued': '⏳ 順番待ち（{position}番目）',
    'status.thinking': '🤔 考え中…',
    'status.writing': '✍️ 回答を作成中…',
    'status.stopped': '⏹ 停止しました。',
    'status.interrupted': '⚠️ 回答が中断されました。もう一度質問してください。',
    'error.generic': '⚠️ 問題が発生しました。もう一度お試しください。',
    'error.timeout': '⚠️ 時間がかかりすぎました。もう一度お試しください。',
    'error.llm': '⚠️ アシスタントは現在利用できません。後でお試しください。',
    'error.busy': '⏳ このチャットでまだ回答中です。お待ちいただくか、停止を押してください。',
    'error.rateLimited': '⏳ メッセージが多すぎます。数分お待ちください。',
    'error.budget': '本日のアシスタント利用上限に達しました。明日またお試しください。',
    'error.budgetUntil': '本日のアシスタント利用上限に達しました。{time} にリセットされます。',
    'error.textOnly': 'テキストメッセージのみ読み取れます。',
    'error.tooLong': 'メッセージが長すぎます（最大{max}文字）。',
    'error.notLinked': 'アシスタントを使うには、まずBandejaアカウントを連携してください。',
    'answer.empty': '（回答なし）',
    'button.newChat': '🆕 新しいチャット',
    'button.chats': '💬 チャット',
    'button.stop': '⏹ 停止',
    'button.exit': '🚪 終了',
    'button.confirm': '✅ 今回だけ許可',
    'button.reject': '✖ 拒否',
    'button.prev': '◀',
    'button.next': '▶',
    'newChat.started': '🆕 新しいチャットを開始しました。何をお手伝いしましょうか？',
    'chats.title': '💬 あなたのチャット（{page}/{pages}）。タップして切り替え：',
    'chats.empty': 'まだチャットはありません。質問を入力してください。',
    'chats.untitled': '新しいチャット',
    'chats.switched': '💬「{title}」に切り替えました。',
    'chats.you': 'あなた',
    'chats.assistant': 'アシスタント',
    'chats.noMessages': 'まだメッセージはありません。質問を入力してください。',
    'exit.done': 'アシスタントモードを終了しました。/ai で戻れます。',
    'action.expires': '確認をお待ちしています。',
    'action.confirmed': '✅ 確認済み',
    'action.rejected': '✖ キャンセル済み',
    'action.gone': 'この操作はもう利用できません。',
    'action.notAvailable': 'Telegramからの確認はまだ利用できません。アプリを開いてください（マイ → AI）。',
    'toast.stopping': '停止中…',
    'toast.gone': 'もう利用できません',
    'button.alwaysAllow': '♾ 常に許可',
    'button.permissions': '🔐 権限',
    'action.remembered': '♾ 今後「{tool}」は確認なしで実行されます。',
    'action.autoApproved': '✅ 自動で実行しました（「{tool}」を許可済み）。',
    'memory.saved': '🧠 メモリーに保存しました：{description}。アプリで確認・削除できます（AI → アシスタント設定 → メモリー）。',
    'action.cannotAlwaysAllow': 'この操作は毎回確認が必要です。「今回だけ許可」をタップしてください。',
    'perm.title': 'アシスタントの権限',
    'perm.hint': 'ツールをタップすると「確認する」と「常に許可」を切り替えます。「常に許可」はタップを省くだけで、アシスタントは引き続き権限を確認します。🔒 のツールは毎回確認します。',
    'perm.ask': '確認する',
    'perm.always': '常に許可',
    'perm.locked': '毎回確認',
    'perm.lockedAlert': '🔒 このツールは毎回確認が必要です。',
    'perm.empty': '変更を行うアシスタントのツールはありません。',
    'perm.resetAll': '↺ すべてリセット',
    'perm.resetConfirm': 'すべてのツールを「確認する」に戻しますか？',
    'perm.resetYes': 'はい、リセット',
    'perm.back': '← 戻る',
    'perm.resetDone': 'すべてのツールで再び確認します',
    'perm.nowAlways': '♾ {tool}：常に許可',
    'perm.nowAsk': '❔ {tool}：確認する',
    'booking.state.CONFIRMED': '確定',
    'booking.state.CANCELLED': 'キャンセル済み',
    'booking.state.PAST': '終了',
    'booking.state.UNKNOWN': '状態不明',
    'booking.cancellable': 'キャンセル可能',
    'entity.more': '…ほか {count} 件',
    'button.openInApp': '📱 アプリで開く',
    'button.connectedClubs': '🔌 連携済みクラブ',
    'action.clientOnly': 'この変更はアプリで実行します。「アプリで開く」をタップして確認してください。',
    'action.clientRequired': 'この変更はアプリでのみ実行できます。アプリを開いて確認してください。',
    'action.unknown': '⚠️ 結果不明 — 連携済みクラブを確認してください',
    'action.partial': '⚠️ 一部のみ完了',
    'web.search': '🔎 ウェブ検索（{provider}）',
    'web.searchCached': '🔎 ウェブ検索（{provider}、キャッシュ）',
    'web.unavailable': '🔎 ウェブ検索は利用できません',
    'web.read': '📄 読んだページ:',
  },
};

export const AGENT_BOT_LANGUAGES = Object.keys(COPY);

/** `t(key, lang)` for the Telegram assistant. Unknown language falls back to English. */
export function agentBotT(
  key: AgentBotCopyKey,
  language: string | null | undefined,
  params: Record<string, string | number> = {},
): string {
  const lang = language && COPY[language] ? language : 'en';
  const template = COPY[lang][key] ?? EN[key] ?? key;
  return Object.entries(params).reduce((acc, [name, value]) => acc.split(`{${name}}`).join(String(value)), template);
}
