export const MAX_PINNED_CHATS = 5;
export const CHAT_LIST_THREAD_INDEX_LIVE_MERGE_MS = 72;

export const CHAT_LIST_VIRTUAL_THRESHOLD = 40;
export const CHAT_LIST_VIRTUAL_OVERSCAN = 8;
export const CHAT_LIST_CHAT_ROW_ESTIMATE_PX = 82;
export const CHAT_LIST_CONTACT_ROW_ESTIMATE_PX = 64;
export const CHAT_LIST_MARKET_GROUP_CHANNEL_THRESHOLD = 24;
export const CHAT_LIST_SEARCH_RESULT_ROW_ESTIMATE_PX = 76;
