const COUNTRY_TO_FLAG: Record<string, string> = {
  Portugal: '🇵🇹',
  Spain: '🇪🇸',
  Serbia: '🇷🇸',
  Russia: '🇷🇺',
  'United Kingdom': '🇬🇧',
  UK: '🇬🇧',
  Germany: '🇩🇪',
  France: '🇫🇷',
  Italy: '🇮🇹',
  Netherlands: '🇳🇱',
  Belgium: '🇧🇪',
  Austria: '🇦🇹',
  Switzerland: '🇨🇭',
  Poland: '🇵🇱',
  Greece: '🇬🇷',
  Turkey: '🇹🇷',
  Croatia: '🇭🇷',
  Slovenia: '🇸🇮',
  'Czech Republic': '🇨🇿',
  Czechia: '🇨🇿',
  Slovakia: '🇸🇰',
  Hungary: '🇭🇺',
  Romania: '🇷🇴',
  Bulgaria: '🇧🇬',
  Ukraine: '🇺🇦',
  'United States': '🇺🇸',
  USA: '🇺🇸',
  'United States of America': '🇺🇸',
  Canada: '🇨🇦',
  Mexico: '🇲🇽',
  Brazil: '🇧🇷',
  Argentina: '🇦🇷',
  Chile: '🇨🇱',
  Colombia: '🇨🇴',
  Peru: '🇵🇪',
  Morocco: '🇲🇦',
  Egypt: '🇪🇬',
  'South Africa': '🇿🇦',
  India: '🇮🇳',
  China: '🇨🇳',
  Japan: '🇯🇵',
  'South Korea': '🇰🇷',
  Korea: '🇰🇷',
  Australia: '🇦🇺',
  'New Zealand': '🇳🇿',
  UAE: '🇦🇪',
  'United Arab Emirates': '🇦🇪',
  Qatar: '🇶🇦',
  'Saudi Arabia': '🇸🇦',
  Israel: '🇮🇱',
  Malta: '🇲🇹',
  Cyprus: '🇨🇾',
  Ireland: '🇮🇪',
  Sweden: '🇸🇪',
  Norway: '🇳🇴',
  Denmark: '🇩🇰',
  Finland: '🇫🇮',
  Iceland: '🇮🇸',
  Estonia: '🇪🇪',
  Latvia: '🇱🇻',
  Lithuania: '🇱🇹',
  Luxembourg: '🇱🇺',
  Monaco: '🇲🇨',
  Andorra: '🇦🇩',
  Montenegro: '🇲🇪',
  'North Macedonia': '🇲🇰',
  Macedonia: '🇲🇰',
  Albania: '🇦🇱',
  Bosnia: '🇧🇦',
  'Bosnia and Herzegovina': '🇧🇦',
  Moldova: '🇲🇩',
  Belarus: '🇧🇾',
  Georgia: '🇬🇪',
  Armenia: '🇦🇲',
  Azerbaijan: '🇦🇿',
  Kazakhstan: '🇰🇿',
  Indonesia: '🇮🇩',
  Malaysia: '🇲🇾',
  Singapore: '🇸🇬',
  Thailand: '🇹🇭',
  Philippines: '🇵🇭',
  Vietnam: '🇻🇳',
  Pakistan: '🇵🇰',
  Bangladesh: '🇧🇩',
  'Sri Lanka': '🇱🇰',
  Nigeria: '🇳🇬',
  Kenya: '🇰🇪',
  Ghana: '🇬🇭',
  Tunisia: '🇹🇳',
  Algeria: '🇩🇿',
  Venezuela: '🇻🇪',
  Ecuador: '🇪🇨',
  Uruguay: '🇺🇾',
  Paraguay: '🇵🇾',
  Bolivia: '🇧🇴',
  'Costa Rica': '🇨🇷',
  Panama: '🇵🇦',
  Cuba: '🇨🇺',
  'Dominican Republic': '🇩🇴',
  'Puerto Rico': '🇵🇷',
  Jamaica: '🇯🇲',
  Trinidad: '🇹🇹',
  'Trinidad and Tobago': '🇹🇹',
  Guatemala: '🇬🇹',
  Honduras: '🇭🇳',
  'El Salvador': '🇸🇻',
  Nicaragua: '🇳🇮',
};

const DEFAULT_FLAG = '🌐';

const LANGUAGE_CODE_TO_COUNTRY: Record<string, string> = {
  en: 'United Kingdom',
  es: 'Spain',
  ru: 'Russia',
  sr: 'Serbia',
  fr: 'France',
  de: 'Germany',
  it: 'Italy',
  pt: 'Portugal',
  nl: 'Netherlands',
  pl: 'Poland',
  cs: 'Czech Republic',
  sk: 'Slovakia',
  hr: 'Croatia',
  bg: 'Bulgaria',
  ro: 'Romania',
  hu: 'Hungary',
  el: 'Greece',
  tr: 'Turkey',
  ar: 'Saudi Arabia',
  zh: 'China',
  ja: 'Japan',
  ko: 'South Korea',
};

export function getCountryFlag(countryName: string): string {
  if (!countryName?.trim()) return DEFAULT_FLAG;
  const normalized = countryName.trim();
  return COUNTRY_TO_FLAG[normalized] ?? COUNTRY_TO_FLAG[normalized.toLowerCase().replace(/\b\w/g, (c) => c.toUpperCase())] ?? DEFAULT_FLAG;
}

export function getLanguageFlag(languageCode: string): string {
  if (!languageCode?.trim()) return DEFAULT_FLAG;
  const code = languageCode.trim().toLowerCase().split('-')[0];
  const country = LANGUAGE_CODE_TO_COUNTRY[code];
  return country ? getCountryFlag(country) : DEFAULT_FLAG;
}
