/** Land-border adjacency for city-selector tint GeoJSON (110m). */

export const COUNTRY_ADJACENCY: Readonly<Record<string, readonly string[]>> = {
  Albania: ['Greece', 'Montenegro', 'North Macedonia'],
  Austria: ['Czechia', 'Germany', 'Hungary', 'Italy', 'Slovakia', 'Slovenia', 'Switzerland'],
  'Bosnia and Herzegovina': ['Croatia', 'Montenegro', 'Serbia'],
  Bulgaria: ['Greece', 'North Macedonia', 'Romania', 'Serbia', 'Turkey'],
  Croatia: ['Bosnia and Herzegovina', 'Hungary', 'Montenegro', 'Serbia', 'Slovenia'],
  Cyprus: [],
  Czechia: ['Austria', 'Germany', 'Poland', 'Slovakia'],
  Denmark: ['Germany'],
  Estonia: ['Latvia'],
  Finland: ['Norway', 'Russia', 'Sweden'],
  France: ['Germany', 'Italy', 'Spain', 'Switzerland'],
  Germany: ['Austria', 'Czechia', 'Denmark', 'France', 'Netherlands', 'Poland', 'Switzerland'],
  Greece: ['Albania', 'Bulgaria', 'North Macedonia', 'Turkey'],
  Hungary: ['Austria', 'Croatia', 'Romania', 'Serbia', 'Slovakia', 'Slovenia'],
  Ireland: ['United Kingdom'],
  Italy: ['Austria', 'France', 'Slovenia', 'Switzerland'],
  Latvia: ['Estonia', 'Lithuania', 'Russia'],
  Lithuania: ['Latvia', 'Poland', 'Russia'],
  Malta: [],
  Moldova: ['Romania'],
  Montenegro: ['Albania', 'Bosnia and Herzegovina', 'Croatia', 'Serbia'],
  Netherlands: ['Germany'],
  'North Macedonia': ['Albania', 'Bulgaria', 'Greece', 'Serbia'],
  Norway: ['Finland', 'Russia', 'Sweden'],
  Poland: ['Czechia', 'Germany', 'Lithuania', 'Russia', 'Slovakia'],
  Portugal: ['Spain'],
  Romania: ['Bulgaria', 'Hungary', 'Moldova', 'Serbia'],
  Russia: ['Finland', 'Latvia', 'Lithuania', 'Norway', 'Poland'],
  Serbia: [
    'Bosnia and Herzegovina',
    'Bulgaria',
    'Croatia',
    'Hungary',
    'Montenegro',
    'North Macedonia',
    'Romania',
  ],
  Slovakia: ['Austria', 'Czechia', 'Hungary', 'Poland'],
  Slovenia: ['Austria', 'Croatia', 'Hungary', 'Italy'],
  'South Africa': [],
  Spain: ['France', 'Portugal'],
  Sweden: ['Finland', 'Norway'],
  Switzerland: ['Austria', 'France', 'Germany', 'Italy'],
  Turkey: ['Bulgaria', 'Greece'],
  'United Kingdom': ['Ireland'],
};
