/** Land-border adjacency for city-selector tint GeoJSON (110m). */

export const COUNTRY_ADJACENCY: Readonly<Record<string, readonly string[]>> = {
  Albania: ['Greece', 'Montenegro', 'North Macedonia'],
  Austria: ['Czechia', 'Germany', 'Hungary', 'Italy', 'Slovakia', 'Slovenia', 'Switzerland'],
  Belarus: ['Latvia', 'Lithuania', 'Poland', 'Russia', 'Ukraine'],
  'Bosnia and Herzegovina': ['Croatia', 'Montenegro', 'Serbia'],
  Bulgaria: ['Greece', 'North Macedonia', 'Romania', 'Serbia', 'Turkey'],
  Croatia: ['Bosnia and Herzegovina', 'Hungary', 'Montenegro', 'Serbia', 'Slovenia'],
  Cyprus: [],
  Czechia: ['Austria', 'Germany', 'Poland', 'Slovakia'],
  Denmark: ['Germany'],
  Estonia: ['Latvia'],
  Finland: ['Norway', 'Russia', 'Sweden'],
  France: ['Germany', 'Italy', 'Spain', 'Switzerland'],
  Germany: ['Austria', 'Czechia', 'Denmark', 'France', 'Netherlands', 'Poland', 'Switzerland'],
  Greece: ['Albania', 'Bulgaria', 'North Macedonia', 'Turkey'],
  Hungary: ['Austria', 'Croatia', 'Romania', 'Serbia', 'Slovakia', 'Slovenia'],
  Ireland: ['United Kingdom'],
  Israel: [],
  Italy: ['Austria', 'France', 'Slovenia', 'Switzerland'],
  Kazakhstan: ['Russia'],
  Latvia: ['Belarus', 'Estonia', 'Lithuania', 'Russia'],
  Lithuania: ['Belarus', 'Latvia', 'Poland', 'Russia'],
  Malta: [],
  Moldova: ['Romania', 'Ukraine'],
  Montenegro: ['Albania', 'Bosnia and Herzegovina', 'Croatia', 'Serbia'],
  Netherlands: ['Germany'],
  'North Macedonia': ['Albania', 'Bulgaria', 'Greece', 'Serbia'],
  Norway: ['Finland', 'Russia', 'Sweden'],
  Poland: ['Belarus', 'Czechia', 'Germany', 'Lithuania', 'Russia', 'Slovakia', 'Ukraine'],
  Portugal: ['Spain'],
  Romania: ['Bulgaria', 'Hungary', 'Moldova', 'Serbia', 'Ukraine'],
  Russia: ['Belarus', 'Finland', 'Kazakhstan', 'Latvia', 'Lithuania', 'Norway', 'Poland', 'Ukraine'],
  Serbia: [
    'Bosnia and Herzegovina',
    'Bulgaria',
    'Croatia',
    'Hungary',
    'Montenegro',
    'North Macedonia',
    'Romania',
  ],
  Slovakia: ['Austria', 'Czechia', 'Hungary', 'Poland'],
  Slovenia: ['Austria', 'Croatia', 'Hungary', 'Italy'],
  'South Africa': [],
  Spain: ['France', 'Portugal'],
  Sweden: ['Finland', 'Norway'],
  Switzerland: ['Austria', 'France', 'Germany', 'Italy'],
  Turkey: ['Bulgaria', 'Greece'],
  Ukraine: ['Belarus', 'Moldova', 'Poland', 'Romania', 'Russia'],
  'United Arab Emirates': ['Oman', 'Saudi Arabia'],
  'United Kingdom': ['Ireland'],
  'Saudi Arabia': ['Oman', 'United Arab Emirates', 'Yemen'],
  Oman: ['Saudi Arabia', 'United Arab Emirates', 'Yemen'],
  Yemen: ['Oman', 'Saudi Arabia'],

  Argentina: ['Bolivia', 'Brazil', 'Chile', 'Paraguay', 'Uruguay'],
  Bolivia: ['Argentina', 'Brazil', 'Chile', 'Paraguay', 'Peru'],
  Brazil: [
    'Argentina',
    'Bolivia',
    'Colombia',
    'Guyana',
    'Paraguay',
    'Peru',
    'Suriname',
    'Uruguay',
    'Venezuela',
  ],
  Chile: ['Argentina', 'Bolivia', 'Peru'],
  Colombia: ['Brazil', 'Ecuador', 'Peru', 'Venezuela'],
  Ecuador: ['Colombia', 'Peru'],
  Guyana: ['Brazil', 'Suriname', 'Venezuela'],
  Paraguay: ['Argentina', 'Bolivia', 'Brazil'],
  Peru: ['Bolivia', 'Brazil', 'Chile', 'Colombia', 'Ecuador'],
  Suriname: ['Brazil', 'Guyana'],
  Uruguay: ['Argentina', 'Brazil'],
  Venezuela: ['Brazil', 'Colombia', 'Guyana'],

  Georgia: ['Armenia', 'Russia', 'Turkey'],
  Armenia: ['Georgia', 'Turkey'],
  Guernsey: [],
};
